export const startOfWeek = (date = new Date()) => { const d = new Date(date); const day = (d.getDay() + 6) % 7; d.setHours(0, 0, 0, 0); d.setDate(d.getDate() - day); return d; };
export const endOfWeek = date => { const d = startOfWeek(date); d.setDate(d.getDate() + 7); return d; };
export const sameDay = (a, b = new Date()) => new Date(a).toDateString() === new Date(b).toDateString();
export function weekSessions(db, date = new Date()) { const start = startOfWeek(date).getTime(), end = endOfWeek(date).getTime(); return db.sessions.filter(s => { const t = new Date(s.startedAt).getTime(); return t >= start && t < end; }); }
export const minutesFor = (sessions, area, subarea = null) => sessions.filter(s => s.area === area && (!subarea || s.subarea === subarea)).reduce((total, s) => total + Number(s.executedMinutes || 0), 0);
export const validSessionsFor = (sessions, area, subarea = null) => sessions.filter(s => s.area === area && (!subarea || s.subarea === subarea) && s.validFrequencySession).length;
export function workExpectedNow(date = new Date()) { const day = (date.getDay() + 6) % 7, ends = [240, 480, 720, 960, 1200, 1320, 1440]; const prev = day ? ends[day - 1] : 0; return prev + (ends[day] - prev) * ((date.getHours() * 60 + date.getMinutes()) / 1440); }
export function getAreaState(db, area, date = new Date()) { const settings = db.settings, done = minutesFor(weekSessions(db, date), area), goal=settings.goals[area]; if (area === "lazer" || !goal || !Number(goal.targetMinutes)) return { done, state: "Livre", expected: 0, ratio: 1, minimum: 0, target: 0 }; const expected = area === "trabalho" ? workExpectedNow(date) : ((date - startOfWeek(date)) / 604800000) * goal.targetMinutes, ratio = expected ? done / expected : 1; let state = ratio < settings.rhythmThresholds.critical ? "Criticamente atrasada" : ratio < settings.rhythmThresholds.behind ? "Atrasada" : ratio <= settings.rhythmThresholds.onTrack ? "Em ritmo" : "Adiantada"; if (done >= goal.targetMinutes) state = "Meta atingida"; else if (done >= goal.minimumMinutes) state = "Mínimo atingido"; return { done, state, expected, ratio, minimum: goal.minimumMinutes, target: goal.targetMinutes }; }
export function isValidFrequencySession(session, settings) { const n = Number(session.executedMinutes || 0); if (session.area === "organizacao") return n >= settings.goals.organizacao.validSessionMinutes; if (session.area === "leitura") return n >= settings.goals.leitura.validSessionMinutes; if (session.area === "estudo") return n >= settings.studyFrequency[session.subarea]?.validSessionMinutes; if (session.area === "trabalho" && settings.strategicWork[session.subarea]) return n >= settings.strategicWork[session.subarea].validSessionMinutes; return false; }
export function studyRows(db, date = new Date()) { const sessions = weekSessions(db, date); return Object.entries(db.settings.studyFrequency).map(([subarea, goal]) => ({ subarea, minutes: minutesFor(sessions, "estudo", subarea), sessions: validSessionsFor(sessions, "estudo", subarea), goal: goal.sessions })); }
export function getAlerts(db, date = new Date()) { const sessions = weekSessions(db, date), alerts = [], work = getAreaState(db, "trabalho", date); if (["Criticamente atrasada", "Atrasada"].includes(work.state)) alerts.push("Trabalho está abaixo do ritmo semanal."); if (validSessionsFor(sessions, "organizacao") < db.settings.goals.organizacao.minimumSessions) alerts.push("Organização ainda está abaixo de cinco sessões."); for (const row of studyRows(db, date)) if (row.sessions < row.goal) alerts.push(`${row.subarea === "piano" ? "Piano" : row.subarea.replace("_", " ")} ainda precisa de sessões.`); for (const sub of ["marketing", "desenvolvimento_empresa"]) if (validSessionsFor(sessions, "trabalho", sub) < 1) alerts.push(`${sub === "marketing" ? "Marketing" : "Desenvolvimento"} ainda precisa de uma sessão estratégica.`); if (["Criticamente atrasada", "Atrasada"].includes(getAreaState(db, "leitura", date).state)) alerts.push("Leitura está se acumulando para o fim da semana."); return alerts.slice(0, 5); }
