const KEY="proxima-acao-mobile";
let db=load(),page="hoje",rec=null;
if(db)applyMobileTaxonomy();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||null}catch{return null}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function applyMobileTaxonomy(){const taxonomy=db?.settings?.taxonomy;if(!taxonomy)return;(taxonomy.customAreas||[]).forEach(area=>{AREAS[area]=taxonomy.areaLabels?.[area]||area;AREA_LABELS[area]=AREAS[area];SUBAREAS[area]=[]});Object.entries(taxonomy.areaLabels||{}).forEach(([area,label])=>{if(AREAS[area]&&label){AREAS[area]=label;AREA_LABELS[area]=label}});Object.entries(taxonomy.customSubareas||{}).forEach(([area,subareas])=>{if(!SUBAREAS[area])return;SUBAREAS[area].push(...subareas.filter(subarea=>!SUBAREAS[area].includes(subarea)))});Object.entries(taxonomy.subareaLabels||{}).forEach(([subarea,label])=>{if(label)SUBAREA_LABELS[subarea]=label})}
function min(value){value=Math.round(value||0);return value>=60?`${Math.floor(value/60)}h${value%60?` ${value%60}min`:""}`:`${value} min`}
function esc(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]))}
function label(value){return AREA_LABELS[value]||SUBAREA_LABELS[value]||value}
function toast(text){const el=document.querySelector("#toast");el.textContent=text;el.style.display="block";setTimeout(()=>el.style.display="none",2800)}
function input(){return db.preferences||{duration:30,energy:2,contexts:["computador","internet"]}}
function activeTasks(){return db.tasks.filter(task=>!["concluida","arquivada"].includes(task.status))}
function today(){const sessions=weekSessions(db),work=minutesFor(sessions.filter(session=>sameDay(session.startedAt)),"trabalho"),pending=db.tasks.filter(task=>isMonthlyRequired(task)&&!isMonthlyCompleted(task)).length;return `<p class="eyebrow">HOJE</p><h1>Próxima ação, sem complicação.</h1><section class="summary"><div><small>Trabalho hoje</small><strong>${min(work)}</strong></div><div><small>Obrigatórias pendentes</small><strong>${pending}</strong></div></section><section class="panel"><b>Escolha, execute ou registre o que já fez.</b><p class="sync-note">Cadastros e organização ficam no desktop. Use Sincronizar para levar suas sessões de volta.</p></section><button class="primary large" data-a="choose">Escolher próxima ação →</button><button class="secondary large" data-a="tasks">Escolher na lista</button><button class="secondary large" data-a="log">Registrar ação feita</button>`}
function chooser(){const preferences=input();return `<p class="eyebrow">ESCOLHER</p><h1>O que faz sentido agora?</h1><section class="card"><b>Tempo disponível</b><div class="choices">${[15,30,60].map(value=>`<button class="choice ${preferences.duration===value?"selected":""}" data-set="duration" data-v="${value}">${value} min</button>`).join("")}</div><b>Energia</b><div class="choices">${[[1,"Baixa"],[2,"Média"],[3,"Alta"]].map(([value,text])=>`<button class="choice ${preferences.energy===value?"selected":""}" data-set="energy" data-v="${value}">${text}</button>`).join("")}</div><b>Contextos</b><div class="chips">${CONTEXTS.map(context=>`<button class="choice ${preferences.contexts.includes(context)?"selected":""}" data-c="${context}">${CONTEXT_LABELS[context]}</button>`).join("")}</div><button class="primary large" data-a="recommend">Ver recomendação</button><button class="secondary large" data-a="tasks">Escolher da lista</button></section>`}
function result(){if(!rec)return chooser();if(rec.empty)return `<h1>Nenhuma ação compatível</h1><p>${rec.message}</p><button class="primary" data-a="choose">Alterar condições</button><button class="secondary large" data-a="tasks">Escolher da lista</button>`;const task=rec.task;return `<p class="eyebrow">SUA PRÓXIMA AÇÃO</p><section class="card task"><span>${label(task.area)} · ${label(task.subarea)}</span><h1>${esc(task.title)}</h1><p>${input().duration} min · energia ${ENERGY_LABELS[task.energyRequired]}</p><ul class="reasons">${rec.reasons.map(reason=>`<li>${esc(reason)}</li>`).join("")}</ul></section><button class="primary large" data-a="start" data-id="${task.id}">Começar</button><button class="secondary large" data-a="tasks">Escolher da lista</button><button class="secondary large" data-a="choose">Alterar condições</button>`}
function tasks(){const items=activeTasks();return `<p class="eyebrow">TAREFAS</p><h1>Escolha o que já sabe que fará.</h1><p class="sync-note">Para criar ou editar tarefas, use a versão desktop.</p><section class="task-list-mobile">${items.length?items.map(task=>`<article class="card task-mobile"><div><b>${esc(task.title)}</b><p>${label(task.area)} · ${label(task.subarea)} · ${task.minimumBlockMinutes} min</p></div><button class="primary" data-a="start" data-id="${task.id}">Iniciar</button></article>`).join(""):`<section class="panel">Nenhuma tarefa aberta neste pacote. Atualize-o no desktop.</section>`}</section>`}
function log(){const area="trabalho";return `<p class="eyebrow">REGISTRAR</p><h1>Ação feita</h1><p class="sync-note">Registre uma ação avulsa. No desktop, ela poderá virar uma tarefa pendente.</p><form id="mobile-log-form" class="card mobile-form"><label>Título<input name="title" required></label><label>Área<select name="area" id="log-area">${Object.entries(AREAS).map(([value,text])=>`<option value="${value}" ${value===area?"selected":""}>${text}</option>`).join("")}</select></label><label>Subárea<select name="subarea" id="log-subarea">${SUBAREAS[area].map(value=>`<option value="${value}">${label(value)}</option>`).join("")}</select></label><label>Duração (min)<input name="duration" type="number" min="1" max="1440" value="30" required></label><button class="primary large" type="submit">Registrar</button></form>`}
function focus(){const current=db.currentSession,task=db.tasks.find(item=>item.id===current.taskId),completion=isMonthlyRequired(task)?"Concluir ciclo mensal":"Concluir tarefa";return `<p class="eyebrow">BLOCO EM ANDAMENTO</p><h1>${esc(current.taskTitleSnapshot)}</h1><p>${label(current.area)} · ${current.plannedMinutes} min planejados</p><div class="timer" id="timer">--:--</div><div class="stack"><button class="primary" data-a="finish" data-r="concluida">${completion}</button><button class="secondary" data-a="finish" data-r="avancou">Avancei, mas ainda falta</button><button class="secondary" data-a="finish" data-r="interrompida">Fui interrompido</button><button class="danger" data-a="finish" data-r="cancelada">Cancelar bloco</button></div>`}
function sync(){return `<p class="eyebrow">SINCRONIZAR</p><h1>Arquivos, sem nuvem.</h1><section class="card"><h3>Receber pacote do desktop</h3><p class="sync-note">Importe o arquivo preparado no computador. Ele substitui somente os dados deste iPhone.</p><label class="file">Importar pacote<input id="package" type="file" accept="application/json" hidden></label></section><section class="card"><h3>Enviar atualizações ao desktop</h3><p class="sync-note">Exporte sessões, conclusões mensais e ações avulsas registradas aqui.</p><button class="primary" data-a="export">Exportar atualização</button></section>`}
function render(){const body=!db?sync():db.currentSession?focus():page==="hoje"?today():page==="choose"?rec?result():chooser():page==="tasks"?tasks():page==="log"?log():sync();document.querySelector("#app").innerHTML=`<div class="app"><div class="brand">→ Próxima Ação</div>${body}</div><nav class="nav">${[["hoje","Hoje"],["choose","Escolher"],["tasks","Tarefas"],["log","Registrar"],["sync","Sincronizar"]].map(([id,text])=>`<button data-a="nav" data-p="${id}" class="${page===id?"active":""}">${text}</button>`).join("")}</nav>`;bind();addManualDateInput();if(db?.currentSession)tick()}
function localDateInput(date=new Date()){return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function timestampForRecordedDay(value){const date=value?new Date(`${value}T12:00:00`):new Date();return Number.isNaN(date.getTime())?new Date().toISOString():date.toISOString()}
function addManualDateInput(){const form=document.querySelector("#mobile-log-form");if(!form||form.querySelector("[name=completedOn]"))return;const field=document.createElement("label");field.innerHTML=`Dia em que foi feita<input name="completedOn" type="date" value="${localDateInput()}">`;form.querySelector("[name=duration]").closest("label").before(field)}
function start(taskId){const task=db.tasks.find(item=>item.id===taskId);if(!task)return;db.currentSession={...createSession({taskId:task.id,taskTitleSnapshot:task.title,area:task.area,subarea:task.subarea,plannedMinutes:input().duration,initialEnergy:input().energy,availableContexts:input().contexts,recommendationSource:"lista"}),startedAt:new Date().toISOString()};task.status="em_andamento";task.updatedAt=new Date().toISOString();save();render()}
function finish(result){const current=db.currentSession,task=db.tasks.find(item=>item.id===current.taskId),done=Math.max(1,Math.floor((Date.now()-new Date(current.startedAt))/60000)),session={...current,endedAt:new Date().toISOString(),executedMinutes:done,pauseMinutes:result==="concluida"?Math.max(0,current.plannedMinutes-done):0,result,interrupted:result==="interrompida"};session.validFrequencySession=isValidFrequencySession(session,db.settings);db.sessions.push(session);task.lastExecutedAt=session.endedAt;task.updatedAt=session.endedAt;if(result==="concluida"&&isMonthlyRequired(task))completeMonthlyCycle(task);else if(result==="concluida")task.status="concluida";else if(result!=="cancelada")task.status="em_andamento";db.currentSession=null;rec=null;page="hoje";save();toast("Sessão registrada.")}
function bind(){document.querySelectorAll("[data-a]").forEach(element=>element.onclick=()=>{const action=element.dataset.a;if(action==="nav"){page=element.dataset.p;rec=null}if(action==="choose"){page="choose";rec=null}if(action==="tasks")page="tasks";if(action==="log")page="log";if(action==="recommend")rec=recommend(db,input());if(action==="start")start(element.dataset.id);if(action==="finish")finish(element.dataset.r);if(action==="export")exportUpdate();render()});document.querySelectorAll("[data-set]").forEach(element=>element.onclick=()=>{db.preferences={...input(),[element.dataset.set]:Number(element.dataset.v)};save();render()});document.querySelectorAll("[data-c]").forEach(element=>element.onclick=()=>{const contexts=new Set(input().contexts);contexts.has(element.dataset.c)?contexts.delete(element.dataset.c):contexts.add(element.dataset.c);db.preferences={...input(),contexts:[...contexts]};save();render()});document.querySelector("#package")?.addEventListener("change",importPackage);const form=document.querySelector("#mobile-log-form"),area=document.querySelector("#log-area"),subarea=document.querySelector("#log-subarea");area?.addEventListener("change",()=>{subarea.innerHTML=(SUBAREAS[area.value]||[]).map(value=>`<option value="${value}">${label(value)}</option>`).join("")});form?.addEventListener("submit",event=>{event.preventDefault();registerLooseAction(form)})}
function registerLooseAction(form){const data=new FormData(form),title=String(data.get("title")||"").trim(),area=data.get("area"),subarea=data.get("subarea"),duration=Math.max(1,Number(data.get("duration")||0));if(!title||!duration){toast("Preencha título e duração.");return}const stamp=timestampForRecordedDay(data.get("completedOn")),session=createSession({taskId:null,taskTitleSnapshot:title,area,subarea,startedAt:stamp,endedAt:stamp,plannedMinutes:duration,executedMinutes:duration,result:"concluida",recommendationSource:"registro_manual_mobile",manualActionId:uid(),notes:"Ação avulsa registrada no celular"});session.validFrequencySession=isValidFrequencySession(session,db.settings);db.sessions.push(session);save();page="hoje";render();toast("Ação registrada. Revise-a no desktop.")}
function tick(){const el=document.querySelector("#timer");if(!el)return;clearInterval(window.mobileTimer);const update=()=>{if(!db.currentSession)return;const elapsed=Math.max(0,Math.floor((Date.now()-new Date(db.currentSession.startedAt))/60000));el.textContent=`${String(Math.floor(elapsed/60)).padStart(2,"0")}:${String(elapsed%60).padStart(2,"0")}`;el.classList.toggle("timer-overtime",elapsed>=db.currentSession.plannedMinutes)};update();window.mobileTimer=setInterval(update,1000)}
async function importPackage(event){try{const packet=JSON.parse(await event.target.files[0].text());if(packet.metadata?.kind!=="mobile-package")throw Error("Escolha um pacote exportado pelo desktop.");db={...packet,cycle:{rejectedTaskIds:[],rejectionCount:0},preferences:{duration:30,energy:2,contexts:["computador","internet"]},currentSession:null};applyMobileTaxonomy();save();page="hoje";toast("Pacote importado.");render()}catch(error){toast(error.message)}}
function exportUpdate(){const update={metadata:{appName:"Próxima Ação",kind:"mobile-update",exportedAt:new Date().toISOString()},sessions:db.sessions,taskUpdates:db.tasks.map(task=>({id:task.id,status:task.status,lastExecutedAt:task.lastExecutedAt,updatedAt:task.updatedAt,recurrence:task.recurrence}))};const anchor=document.createElement("a");anchor.href=URL.createObjectURL(new Blob([JSON.stringify(update,null,2)],{type:"application/json"}));anchor.download=`proxima-acao-mobile-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(anchor.href)}
let mobileAgendaContext=null;
function activeTasks(){return db.tasks.filter(task=>!["concluida","arquivada"].includes(task.status)&&(!mobileAgendaContext?.responsibilityArea||task.responsibilityArea===mobileAgendaContext.responsibilityArea))}
function mobileWeek(){ensureAgendaData(db);const blocks=blocksForWeek(db,new Date()),groups=Object.groupBy?Object.groupBy(blocks,block=>block.date):blocks.reduce((acc,block)=>((acc[block.date]||=[]).push(block),acc),{}),current=currentAgendaState(db).current;return `<p class="eyebrow">SEMANA</p><h1>Onde sua atenção estará?</h1>${current?`<section class="card mobile-agenda-now"><small>AGORA</small><h2>${esc(current.title)}</h2><p>${RESPONSIBILITY_AREAS[current.responsibilityArea]} · ${BLOCK_TYPES[current.blockType]} até ${current.endTime}</p>${["focus","maintenance"].includes(current.blockType)?`<button class="primary large" data-a="agenda-next" data-id="${current.id}">Escolher próxima ação</button>`:""}</section>`:""}<section class="mobile-week-list">${Object.entries(groups).map(([date,items])=>`<div class="mobile-day"><h3>${new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"numeric",month:"short"}).format(new Date(`${date}T12:00:00`))}</h3>${items.map(block=>`<article class="card mobile-schedule-block type-${block.blockType}"><b>${block.startTime}–${block.endTime} · ${esc(block.title)}</b><p>${RESPONSIBILITY_AREAS[block.responsibilityArea]} · ${BLOCK_TYPES[block.blockType]}</p>${["focus","maintenance"].includes(block.blockType)?`<button class="secondary" data-a="agenda-next" data-id="${block.id}">Próxima ação</button>`:""}</article>`).join("")}</div>`).join("")}</section>`}
function agendaMobileChoose(id){let block=blocksForWeek(db,new Date()).find(item=>item.id===id)||db.scheduleBlocks.find(item=>item.id===id);if(!block)return;if(block._virtual){block=saveAgendaBlock(db,{...block,id:null,originalOccurrenceDate:block.date});save()}const remaining=Math.max(15,Math.min(60,(Number(block.endTime.slice(0,2))*60+Number(block.endTime.slice(3)))-(Number(block.startTime.slice(0,2))*60+Number(block.startTime.slice(3)))));mobileAgendaContext={scheduleBlockId:block.id,responsibilityArea:block.responsibilityArea};db.preferences={...input(),duration:remaining>=60?60:remaining>=30?30:15};page="choose";rec=null;save()}
function start(taskId){const task=db.tasks.find(item=>item.id===taskId);if(!task)return;db.currentSession={...createSession({taskId:task.id,scheduleBlockId:mobileAgendaContext?.scheduleBlockId||null,responsibilityArea:mobileAgendaContext?.responsibilityArea||task.responsibilityArea||null,taskTitleSnapshot:task.title,area:task.area,subarea:task.subarea,plannedMinutes:input().duration,initialEnergy:input().energy,availableContexts:input().contexts,recommendationSource:mobileAgendaContext?"agenda":"lista"}),startedAt:new Date().toISOString()};task.status="em_andamento";task.updatedAt=new Date().toISOString();save();render()}
function render(){const body=!db?sync():db.currentSession?focus():page==="hoje"?today():page==="week"?mobileWeek():page==="choose"?rec?result():chooser():page==="tasks"?tasks():page==="log"?log():sync();document.querySelector("#app").innerHTML=`<div class="app"><div class="brand">→ Próxima Ação</div>${mobileAgendaContext&&!db?.currentSession?`<div class="mobile-context">Agenda: ${RESPONSIBILITY_AREAS[mobileAgendaContext.responsibilityArea]} <button data-a="clear-agenda">remover filtro</button></div>`:""}${body}</div><nav class="nav">${[["hoje","Hoje"],["week","Semana"],["choose","Escolher"],["tasks","Tarefas"],["log","Registrar"],["sync","Sincronizar"]].map(([id,text])=>`<button data-a="nav" data-p="${id}" class="${page===id?"active":""}">${text}</button>`).join("")}</nav>`;bind();addManualDateInput();if(db?.currentSession)tick()}
function bind(){document.querySelectorAll("[data-a]").forEach(element=>element.onclick=()=>{const action=element.dataset.a;if(action==="nav"){page=element.dataset.p;rec=null;if(page==="choose"&&!mobileAgendaContext)mobileAgendaContext=null}if(action==="choose"){page="choose";rec=null;mobileAgendaContext=null}if(action==="tasks")page="tasks";if(action==="log")page="log";if(action==="agenda-next")agendaMobileChoose(element.dataset.id);if(action==="clear-agenda"){mobileAgendaContext=null;rec=null}if(action==="recommend"){const source=mobileAgendaContext?{...db,tasks:activeTasks()}:db;rec=recommend(source,{...input(),responsibilityArea:mobileAgendaContext?.responsibilityArea||null})}if(action==="start")start(element.dataset.id);if(action==="finish")finish(element.dataset.r);if(action==="export")exportUpdate();render()});document.querySelectorAll("[data-set]").forEach(element=>element.onclick=()=>{db.preferences={...input(),[element.dataset.set]:Number(element.dataset.v)};save();render()});document.querySelectorAll("[data-c]").forEach(element=>element.onclick=()=>{const contexts=new Set(input().contexts);contexts.has(element.dataset.c)?contexts.delete(element.dataset.c):contexts.add(element.dataset.c);db.preferences={...input(),contexts:[...contexts]};save();render()});document.querySelector("#package")?.addEventListener("change",importPackage);const form=document.querySelector("#mobile-log-form"),area=document.querySelector("#log-area"),subarea=document.querySelector("#log-subarea");area?.addEventListener("change",()=>{subarea.innerHTML=(SUBAREAS[area.value]||[]).map(value=>`<option value="${value}">${label(value)}</option>`).join("")});form?.addEventListener("submit",event=>{event.preventDefault();registerLooseAction(form)})}
function exportUpdate(){const update={metadata:{appName:"Próxima Ação",kind:"mobile-update",databaseVersion:2,exportedAt:new Date().toISOString()},sessions:db.sessions,taskUpdates:db.tasks.map(task=>({id:task.id,status:task.status,lastExecutedAt:task.lastExecutedAt,updatedAt:task.updatedAt,recurrence:task.recurrence}))};const anchor=document.createElement("a");anchor.href=URL.createObjectURL(new Blob([JSON.stringify(update,null,2)],{type:"application/json"}));anchor.download=`proxima-acao-mobile-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(anchor.href)}
if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js?v=5").catch(()=>{});
render();
