const { chromium } = require("C:/Users/thais/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright");
const path = require("path");
const { pathToFileURL } = require("url");

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe" });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  await page.clock.setFixedTime(new Date("2026-07-26T12:00:00Z"));
  page.setDefaultTimeout(15000);
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("console", message => { if (message.type() === "error") errors.push(message.text()); });

  const desktop = pathToFileURL(path.resolve(__dirname, "../index.html")).href;
  await page.goto(desktop);
  console.log("desktop-open");
  await page.waitForSelector(".agenda-today-bridge");
  console.log("today-bridge-ok");
  const todayGeldPlanning = await page.locator(".today-responsibilities span", { hasText: "Geld" }).locator("b").first().textContent();
  await page.click('[data-page="semana"]');
  await page.waitForSelector(".agenda-week-grid");
  console.log("week-grid-ok");
  const weekGeldPlanning = await page.locator(".balance-card", { hasText: "Geld" }).locator("p").first().locator("strong").textContent();
  if (todayGeldPlanning !== weekGeldPlanning) throw new Error(`Hoje e Semana divergem para Geld: ${todayGeldPlanning} / ${weekGeldPlanning}`);
  console.log("planning-reference-consistent-ok");
  const blocksBeforeDayPlan = await page.evaluate(() => JSON.parse(localStorage.getItem("proxima-acao-db")).scheduleBlocks.length);
  await page.click('[data-agenda-action="plan-day"]');
  await page.waitForSelector(".day-plan-modal");
  if (!await page.getByRole("heading", { name:"Planejar o dia" }).count()) throw new Error("Planejador diário não abriu.");
  await page.screenshot({ path: path.resolve(__dirname, "../tmp/day-planner-smoke.png"), fullPage: true });
  if (await page.locator("[data-apply-day-plan]").count()) {
    if (!await page.locator("[data-day-proposal]").count()) throw new Error("Planejador não apresentou os intervalos livres.");
    await page.click("[data-apply-day-plan]");
    const dayPlanDatabase = await page.evaluate(() => JSON.parse(localStorage.getItem("proxima-acao-db")));
    if (dayPlanDatabase.scheduleBlocks.length<=blocksBeforeDayPlan||!dayPlanDatabase.scheduleBlocks.some(block=>block.source==="day-plan")) throw new Error("Propostas do dia não foram aplicadas.");
    const plannedHouseBlock = dayPlanDatabase.scheduleBlocks.find(block=>block.source==="day-plan"&&block.responsibilityArea==="casa");
    if (plannedHouseBlock&&!plannedHouseBlock.plannedRoutineIds?.length) throw new Error("Bloco Casa proposto perdeu as rotinas recomendadas.");
  } else {
    await page.click(".day-plan-modal [data-agenda-close]");
  }
  console.log("day-planner-flow-ok");
  if (await page.locator(".agenda-block").count() < 10) throw new Error("Recorrências padrão não foram materializadas.");

  await page.click('[data-agenda-action="new"]');
  await page.fill('#agenda-block-form [name="title"]', "Teste de integração Agenda");
  await page.selectOption('#agenda-block-form [name="responsibilityArea"]', "geld");
  await page.selectOption('#agenda-block-form [name="blockType"]', "focus");
  await page.click('#agenda-block-form button.primary');
  await page.waitForSelector('text="Teste de integração Agenda"');
  console.log("block-create-ok");
  await page.click('[data-agenda-action="new"]');
  await page.fill('#agenda-block-form [name="title"]', "Bloco Casa operacional");
  await page.selectOption('#agenda-block-form [name="responsibilityArea"]', "casa");
  await page.selectOption('#agenda-block-form [name="area"]', "trabalho");
  await page.selectOption('#agenda-block-form [name="subarea"]', "operacional");
  await page.selectOption('#agenda-block-form [name="blockType"]', "maintenance");
  await page.click('#agenda-block-form button.primary');
  const houseBlock = page.locator('.agenda-block', { hasText: "Bloco Casa operacional" });
  await houseBlock.locator('[data-agenda-action="routines"]').click({ force:true });
  await page.waitForSelector(".maintenance-modal");
  const selectedMaintenance = page.locator(".maintenance-modal [data-select-maintenance]:checked");
  if (!await selectedMaintenance.count()) throw new Error("Seleção recomendada de rotinas ficou vazia.");
  const maintenanceEstimate = await selectedMaintenance.evaluateAll(inputs=>inputs.reduce((sum,input)=>sum+Number(input.dataset.estimate||0),0));
  if (maintenanceEstimate>60) throw new Error(`Seleção de rotinas ultrapassou o bloco: ${maintenanceEstimate} min.`);
  await page.click("[data-start-maintenance]");
  await page.waitForTimeout(200);
  if (!await page.locator(".maintenance-focus-panel").count()) {
    const maintenanceDebug = await page.evaluate(() => ({currentSession:JSON.parse(localStorage.getItem("proxima-acao-db"))?.currentSession,body:document.body.innerText.slice(0,500)}));
    throw new Error(`Bloco Casa não iniciou: ${JSON.stringify(maintenanceDebug)} Erros: ${errors.join(" | ")}`);
  }
  await page.locator("[data-complete-maintenance]").first().check();
  await page.click('[data-action="finish-session"][data-result="avancou"]');
  const maintenanceDatabase = await page.evaluate(() => JSON.parse(localStorage.getItem("proxima-acao-db")));
  const maintenanceSession = maintenanceDatabase.sessions.find(session=>session.recommendationSource==="agenda_maintenance");
  if (!maintenanceSession||maintenanceSession.responsibilityArea!=="casa"||maintenanceSession.area!=="trabalho"||maintenanceSession.subarea!=="operacional"||maintenanceSession.executedMinutes<1) throw new Error("Tempo ou classificação da tarefa do bloco Casa não foi registrado.");
  if (!maintenanceDatabase.maintenanceRoutines.some(routine=>routine.completedDates?.length)) throw new Error("Rotina marcada não foi registrada.");
  const completedRoutine = maintenanceDatabase.maintenanceRoutines.find(routine=>routine.completedDates?.length);
  const completedDateCount = completedRoutine.completedDates.length;
  console.log("maintenance-block-flow-ok");
  await page.click('[data-page="semana"]');
  const completedRoutineRow = page.locator(`[data-maintenance-row="${completedRoutine.id}"]`);
  await completedRoutineRow.locator('[data-agenda-action="edit-maintenance"]').click();
  await page.waitForSelector(".maintenance-routine-modal");
  await page.fill('.maintenance-routine-modal [name="title"]', "Rotina editada");
  await page.selectOption('.maintenance-routine-modal [name="frequencyType"]', "weekly");
  await page.fill('.maintenance-routine-modal [name="frequencyCount"]', "2");
  await page.fill('.maintenance-routine-modal [name="estimatedMinutes"]', "20");
  await page.click(".maintenance-routine-modal button.primary");
  await page.waitForSelector('[data-maintenance-row]:has-text("Rotina editada")');
  page.once("dialog", dialog=>dialog.accept());
  await page.locator('[data-maintenance-row]:has-text("Rotina editada") [data-agenda-action="delete-maintenance"]').click();
  if (await page.locator('[data-maintenance-row]:has-text("Rotina editada")').count()) throw new Error("Rotina excluida permaneceu na lista ativa.");
  await page.locator(".maintenance-archived summary").click();
  await page.locator(`.maintenance-archived [data-agenda-action="restore-maintenance"][data-id="${completedRoutine.id}"]`).click();
  await page.waitForSelector('[data-maintenance-row]:has-text("Rotina editada")');
  const restoredRoutine = await page.evaluate(id => JSON.parse(localStorage.getItem("proxima-acao-db")).maintenanceRoutines.find(routine=>routine.id===id), completedRoutine.id);
  if (!restoredRoutine.active||restoredRoutine.completedDates.length!==completedDateCount) throw new Error("Restauracao da rotina perdeu o historico.");
  console.log("maintenance-edit-delete-restore-ok");
  await page.screenshot({ path: path.resolve(__dirname, "../tmp/agenda-desktop-smoke.png"), fullPage: true });

  await page.click('[data-page="tarefas"]');
  await page.click('[data-action="new-task"]');
  await page.waitForSelector('#task-form [name="responsibilityArea"]');
  console.log("task-responsibility-ok");
  await page.fill('#task-form [name="title"]', "Sessão Geld direta");
  await page.selectOption('#task-form [name="responsibilityArea"]', "geld");
  await page.click('#task-form button.primary');
  const manualGeldTask = await page.evaluate(() => JSON.parse(localStorage.getItem("proxima-acao-db")).tasks.find(task=>task.responsibilityArea==="geld"));
  if (!manualGeldTask) throw new Error("Responsabilidade da tarefa nÃ£o foi salva.");
  await page.click('[data-page="historico"]');
  await page.click('[data-action="register-action"]');
  await page.selectOption('#manual-log-form [name="taskId"]', manualGeldTask.id);
  await page.fill('#manual-log-form [name="duration"]', "25");
  await page.click('#manual-log-form button.primary');
  const manualGeldSession = await page.evaluate(() => JSON.parse(localStorage.getItem("proxima-acao-db")).sessions.at(-1));
  if (manualGeldSession.responsibilityArea!=="geld"||manualGeldSession.executedMinutes!==25) throw new Error("Registro manual nÃ£o levou o tempo para Geld.");
  await page.click('[data-page="tarefas"]');
  await page.locator('.task-row', { hasText: "Sessão Geld direta" }).locator('[data-action="start-session"]').click();
  await page.waitForSelector(".focus");
  await page.click('[data-action="finish-session"][data-result="concluida"]');
  const geldExecutionToday = page.locator(".today-responsibilities span", { hasText: "Geld" });
  const geldExecutionText = await geldExecutionToday.innerText();
  if (!geldExecutionText.includes("26 min")) throw new Error("Tempo real não entrou no indicador da área.");
  if (!geldExecutionText.includes("fora do plano")) throw new Error("Origem fora do plano não foi informada.");
  await page.click('[data-page="semana"]');
  const unplannedBlock = page.locator('.agenda-block.source-unplanned-execution', { hasText: "Sessão Geld direta" });
  await unplannedBlock.waitFor();
  if (!await unplannedBlock.getByText("Execução não planejada").count()) throw new Error("Bloco retroativo não foi identificado.");
  console.log("unplanned-session-block-ok");
  await page.click('[data-page="tarefas"]');
  await page.click('[data-action="new-task"]');
  await page.fill('#task-form [name="title"]', "Campanha Geld");
  await page.selectOption('#task-form [name="responsibilityArea"]', "geld");
  await page.click('#task-form button.primary');
  await page.click('[data-action="new-task"]');
  await page.fill('#task-form [name="title"]', "Curso profissional");
  await page.selectOption('#task-form [name="responsibilityArea"]', "profissional");
  await page.selectOption('#task-form [name="area"]', "estudo");
  await page.click('#task-form button.primary');
  await page.click('[data-page="semana"]');
  const testBlock = page.locator('.agenda-block', { hasText: "Teste de integração Agenda" });
  await testBlock.locator('[data-agenda-action="next"]').evaluate(button=>button.click());
  await page.waitForTimeout(200);
  if (!await page.locator("#agenda-recommendation-context").count()) {
    const testBlockId = await testBlock.getAttribute("data-agenda-block");
    const recommendationDebug = await page.evaluate(id => ({body:document.body.innerText.slice(0,700),currentSession:JSON.parse(localStorage.getItem("proxima-acao-db"))?.currentSession,found:!!findBlock(db,id),context:getAgendaContext(),block:db.scheduleBlocks.find(item=>item.id===id)}),testBlockId);
    throw new Error(`Contexto da Agenda não abriu: ${JSON.stringify(recommendationDebug)} Erros: ${errors.join(" | ")}`);
  }
  await page.click('#recommend-form button[type="submit"]');
  await page.waitForSelector('.recommend-card:has-text("Campanha Geld")');
  if (await page.locator('.recommend-card:has-text("Curso profissional")').count()) throw new Error("Filtro de responsabilidade não foi respeitado.");
  console.log("agenda-recommendation-filter-ok");

  const database = await page.evaluate(() => JSON.parse(localStorage.getItem("proxima-acao-db")));
  const mobile = pathToFileURL(path.resolve(__dirname, "../mobile/index.html")).href;
  await page.goto(mobile);
  await page.evaluate(value => localStorage.setItem("proxima-acao-mobile", JSON.stringify(value)), database);
  await page.reload();
  if (!await page.locator('[data-p="week"]').count()) throw new Error(`Mobile não renderizou. Erros: ${errors.join(" | ")} Conteúdo: ${(await page.locator("body").innerText()).slice(0,300)}`);
  await page.click('[data-p="week"]');
  await page.waitForSelector(".mobile-week-list");
  console.log("mobile-week-ok");
  if (await page.locator(".mobile-schedule-block").count() < 10) throw new Error("Agenda mobile não recebeu os blocos.");

  await page.screenshot({ path: path.resolve(__dirname, "../tmp/agenda-smoke.png"), fullPage: true });
  await browser.close();
  if (errors.length) throw new Error(`Erros do navegador: ${errors.join(" | ")}`);
  console.log("agenda-smoke-ok");
})().catch(error => { console.error(error); process.exit(1); });
