
const DAY_MS=86400000;
let visibleWeek=null;
let activeAgendaContext=null;
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
const localDate=value=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const monday=value=>{const d=new Date(value);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d};
const addDays=(value,amount)=>{const d=new Date(value);d.setDate(d.getDate()+amount);return d};
const minutes=time=>{const [h,m]=String(time||"00:00").split(":").map(Number);return h*60+m};
const duration=block=>Math.max(0,minutes(block.endTime)-minutes(block.startTime));
const formatTime=value=>String(value||"").slice(0,5);
const label=(map,key)=>map[key]||key||"—";

function defaultRecurrences(){return [
 {name:"Período individual",responsibilityArea:"pessoal",blockType:"protected",rigidity:"semiFlexible",daysOfWeek:[1,2,3,4,5],startTime:"05:00",endTime:"06:00"},
 {name:"Rotina do Júlio - manhã",responsibilityArea:"familia",blockType:"presence",rigidity:"rigid",daysOfWeek:[1,2,3,4,5],startTime:"06:00",endTime:"07:30"},
 {name:"Levar Júlio à escola",responsibilityArea:"familia",blockType:"fixed",rigidity:"rigid",daysOfWeek:[1,2,3,4,5],startTime:"07:30",endTime:"07:50"},
 {name:"Exercício corporal",responsibilityArea:"pessoal",blockType:"protected",rigidity:"semiFlexible",daysOfWeek:[1,2,3,4,5],startTime:"08:00",endTime:"09:00"},
 {name:"Período com Júlio",responsibilityArea:"familia",blockType:"presence",rigidity:"rigid",daysOfWeek:[1,2,3,4,5],startTime:"15:00",endTime:"18:00"},
 {name:"Rotina noturna do Júlio",responsibilityArea:"familia",blockType:"presence",rigidity:"rigid",daysOfWeek:[1,2,3,4,5,6,0],startTime:"19:00",endTime:"20:00"},
 {name:"Terapia",responsibilityArea:"pessoal",blockType:"fixed",rigidity:"rigid",daysOfWeek:[2],startTime:"14:30",endTime:"15:30"},
 {name:"Fisioterapia",responsibilityArea:"pessoal",blockType:"fixed",rigidity:"rigid",daysOfWeek:[1,3,5],startTime:"11:30",endTime:"13:00",endDate:"2026-08-31"},
 {name:"Reservável para clientes",responsibilityArea:"geld",blockType:"reservable",rigidity:"semiFlexible",daysOfWeek:[1,2,3,4,5],startTime:"18:00",endTime:"20:00"},
 {name:"Reservável para clientes - sábado",responsibilityArea:"geld",blockType:"reservable",rigidity:"semiFlexible",daysOfWeek:[6],startTime:"08:00",endTime:"14:00"}
].map(item=>({id:uid(),startDate:null,endDate:null,active:true,createdAt:now(),updatedAt:now(),...item}))}

function defaultMaintenance(){const rows=[["Tirar lixo","daily",1,10],["Lavar louça","daily",1,20],["Limpar e ativar robô","daily",1,15],["Guardar objetos fora do lugar","daily",1,15],["Manutenção rápida de pias e vasos","daily",1,15],["Regar plantas","daily",1,10],["Tirar pó e limpar móveis","weekly",3,25],["Lavar banheiros","weekly",1,60],["Passar pano nos pisos","weekly",1,45],["Mercado","weekly",1,60],["Preparar comida da semana","weekly",1,90],["Trocar toalhas","weekly",1,15],["Trocar roupa de cama","monthly",2,25]];return rows.map(([title,type,count,estimatedMinutes])=>({id:uid(),title,responsibilityArea:"casa",frequency:{type,count},estimatedMinutes,preferredDays:[],completedDates:[],lastCompletedAt:null,active:true,createdAt:now(),updatedAt:now()}))}

function ensureAgendaData(db){db.scheduleBlocks=Array.isArray(db.scheduleBlocks)?db.scheduleBlocks:[];db.scheduleRecurrences=Array.isArray(db.scheduleRecurrences)?db.scheduleRecurrences:[];db.maintenanceRoutines=Array.isArray(db.maintenanceRoutines)?db.maintenanceRoutines:[];db.agendaHistory=Array.isArray(db.agendaHistory)?db.agendaHistory:[];db.agendaSettings={...structuredClone(DEFAULT_AGENDA_SETTINGS),...(db.agendaSettings||{}),responsibilities:{...structuredClone(DEFAULT_AGENDA_SETTINGS.responsibilities),...(db.agendaSettings?.responsibilities||{})}};if(!db.agendaSettings.initialized){db.scheduleRecurrences.push(...defaultRecurrences());db.maintenanceRoutines.push(...defaultMaintenance());db.agendaSettings.initialized=true;db.agendaSettings.initializedAt=now()}return db}

function recurrenceOccurs(recurrence,date){const key=localDate(date);if(!recurrence.active||!recurrence.daysOfWeek?.includes(date.getDay()))return false;if(recurrence.startDate&&key<recurrence.startDate)return false;if(recurrence.endDate&&key>recurrence.endDate)return false;return true}
function blocksForWeek(db,reference=new Date()){const start=monday(reference),end=addDays(start,7),manual=db.scheduleBlocks.filter(block=>block.date>=localDate(start)&&block.date<localDate(end)),overrides=new Set(manual.filter(block=>block.recurrenceId).map(block=>`${block.recurrenceId}:${block.originalOccurrenceDate||block.date}`)),virtual=[];for(let day=0;day<7;day++){const date=addDays(start,day),dateKey=localDate(date);for(const recurrence of db.scheduleRecurrences){if(!recurrenceOccurs(recurrence,date)||overrides.has(`${recurrence.id}:${dateKey}`))continue;virtual.push({id:`rec:${recurrence.id}:${dateKey}`,title:recurrence.name,responsibilityArea:recurrence.responsibilityArea,blockType:recurrence.blockType,rigidity:recurrence.rigidity,date:dateKey,startTime:recurrence.startTime,endTime:recurrence.endTime,recurrenceId:recurrence.id,status:"planned",allowNextAction:recurrence.blockType==="focus",source:"recurrence",confirmedExternalEvent:recurrence.blockType==="fixed",notes:"",_virtual:true})}}return [...manual,...virtual].filter(block=>!["cancelled","moved"].includes(block.status)).sort((a,b)=>`${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`))}

function agendaHistory(db,type,block,extra={}){db.agendaHistory.push({id:uid(),type,blockId:block.id,title:block.title,date:block.date,at:now(),...extra})}
function saveAgendaBlock(db,data){const existing=data.id&&!String(data.id).startsWith("rec:")?db.scheduleBlocks.find(block=>block.id===data.id):null,stamp=now(),block={id:existing?.id||uid(),title:data.title?.trim()||label(BLOCK_TYPES,data.blockType),responsibilityArea:data.responsibilityArea||"pessoal",blockType:data.blockType||"focus",rigidity:data.rigidity||"flexible",date:data.date||localDate(new Date()),startTime:data.startTime||"09:00",endTime:data.endTime||"10:00",recurrenceId:data.recurrenceId||null,originalOccurrenceDate:data.originalOccurrenceDate||null,status:data.status||existing?.status||"planned",allowNextAction:data.blockType==="focus"||data.allowNextAction===true,source:data.source||"manual",confirmedExternalEvent:data.blockType==="fixed"||data.confirmedExternalEvent===true,notes:data.notes||"",createdAt:existing?.createdAt||stamp,updatedAt:stamp};if(existing)Object.assign(existing,block);else db.scheduleBlocks.push(block);agendaHistory(db,existing?"updated":"planned",block);return block}
function saveAgendaRecurrence(db,data){const existing=db.scheduleRecurrences.find(item=>item.id===data.id),value={id:existing?.id||uid(),name:data.name||data.title||"Bloco recorrente",responsibilityArea:data.responsibilityArea||"pessoal",blockType:data.blockType||"protected",rigidity:data.rigidity||"semiFlexible",daysOfWeek:(data.daysOfWeek||[]).map(Number),startTime:data.startTime,endTime:data.endTime,startDate:data.startDate||null,endDate:data.endDate||null,active:data.active!==false,createdAt:existing?.createdAt||now(),updatedAt:now()};if(existing)Object.assign(existing,value);else db.scheduleRecurrences.push(value);return value}

function significant(block){return duration(block)>=30||block.blockType==="presence"||block.blockType==="fixed"}
function responsibilityStates(db,reference=new Date()){const current=blocksForWeek(db,reference),all=[...db.scheduleBlocks,...current.filter(block=>block._virtual)],today=new Date(reference);return Object.keys(RESPONSIBILITY_AREAS).map(area=>{const week=current.filter(block=>block.responsibilityArea===area&&!["cancelled","missed"].includes(block.status)),past=all.filter(block=>block.responsibilityArea===area&&significant(block)&&new Date(`${block.date}T${block.endTime}`)<=today).sort((a,b)=>`${b.date}${b.endTime}`.localeCompare(`${a.date}${a.endTime}`)),last=past[0],days=last?Math.floor((today-new Date(`${last.date}T12:00:00`))/DAY_MS):99,planned=week.reduce((sum,block)=>sum+duration(block),0),pendingMaintenance=area==="casa"?db.maintenanceRoutines.filter(item=>item.active&&!item.completedDates?.includes(localDate(today))).length:0;let status="Em equilíbrio",kind="balanced";if(area==="familia"&&week.some(block=>block.blockType==="presence")){status="Bem cuidada";kind="good"}else if(pendingMaintenance>5||days>=7){status="Precisa de atenção";kind="attention"}else if(!week.length||days>=4){status="Pouco presente";kind="low"}else if(planned>=120){status="Bem cuidada";kind="good"}return{area,status,kind,last,days,planned,next:week.find(block=>new Date(`${block.date}T${block.startTime}`)>=today),pendingMaintenance}})}

function currentAgendaState(db,date=new Date()){const blocks=blocksForWeek(db,date),stamp=date.getTime(),current=blocks.find(block=>{const start=new Date(`${block.date}T${block.startTime}`).getTime(),end=new Date(`${block.date}T${block.endTime}`).getTime();return stamp>=start&&stamp<end}),next=blocks.find(block=>new Date(`${block.date}T${block.startTime}`).getTime()>stamp);return{current,next}}
function executedForBlock(db,id){return db.sessions.filter(session=>session.scheduleBlockId===id).reduce((sum,session)=>sum+Number(session.executedMinutes||0),0)}

function blockCard(db,block){const executed=executedForBlock(db,block.id),canAct=block.blockType==="focus"||block.blockType==="maintenance";return `<article class="agenda-block type-${block.blockType} area-${block.responsibilityArea}" data-agenda-block="${esc(block.id)}"><div class="agenda-block-head"><b>${esc(block.title)}</b><span>${formatTime(block.startTime)}–${formatTime(block.endTime)}</span></div><p>${esc(label(RESPONSIBILITY_AREAS,block.responsibilityArea))} · ${esc(label(BLOCK_TYPES,block.blockType))}</p>${executed?`<small>${executed} min executados</small>`:""}<div class="agenda-block-actions">${canAct?`<button data-agenda-action="next" data-id="${esc(block.id)}">Próxima ação</button>`:""}<button data-agenda-action="edit" data-id="${esc(block.id)}">Editar</button><button data-agenda-action="duplicate" data-id="${esc(block.id)}">Duplicar</button>${block.blockType==="reservable"?`<button data-agenda-action="convert" data-id="${esc(block.id)}">Converter</button>`:""}<button data-agenda-action="partial" data-id="${esc(block.id)}">Parcial</button><button data-agenda-action="complete" data-id="${esc(block.id)}">Concluir</button><button data-agenda-action="delete" data-id="${esc(block.id)}">Excluir</button></div></article>`}
function weekGrid(db,reference){const start=monday(reference),blocks=blocksForWeek(db,start),startHour=db.agendaSettings.weekStartHour||5,endHour=db.agendaSettings.weekEndHour||23,slots=(endHour-startHour)*2,headers=Array.from({length:7},(_,index)=>{const date=addDays(start,index);return `<div class="agenda-day-head" style="grid-column:${index+2}"><b>${new Intl.DateTimeFormat("pt-BR",{weekday:"short"}).format(date)}</b><span>${date.getDate()}/${date.getMonth()+1}</span></div>`}).join(""),times=Array.from({length:endHour-startHour+1},(_,index)=>`<div class="agenda-time" style="grid-row:${index*2+2}/span 2">${String(startHour+index).padStart(2,"0")}:00</div>`).join(""),cards=blocks.map(block=>{const date=new Date(`${block.date}T12:00:00`),column=((date.getDay()+6)%7)+2,startSlot=Math.max(0,Math.round((minutes(block.startTime)-startHour*60)/30)),span=Math.max(1,Math.round(duration(block)/30));return `<div class="agenda-position" style="grid-column:${column};grid-row:${startSlot+2}/span ${span}">${blockCard(db,block)}</div>`}).join("");return `<div class="agenda-week-grid" style="--agenda-slots:${slots}"><div class="agenda-corner"></div>${headers}${times}${cards}</div>`}

function balanceCards(db,reference){return `<section class="agenda-balance"><div class="section-title"><h2>Como está sua semana?</h2><span class="subtle">equilíbrio, não igualdade</span></div><div class="agenda-balance-grid">${responsibilityStates(db,reference).map(item=>`<article class="balance-card ${item.kind}"><span class="responsibility-dot area-${item.area}"></span><div><b>${label(RESPONSIBILITY_AREAS,item.area)}</b><p>${item.status}</p><small>${item.last?`Última atenção: ${item.days} dia(s)`:"Sem atenção registrada"}${item.next?` · Próximo: ${new Intl.DateTimeFormat("pt-BR",{weekday:"short",day:"numeric"}).format(new Date(`${item.next.date}T12:00:00`))} ${item.next.startTime}`:""}</small></div></article>`).join("")}</div></section>`}
function maintenancePanel(db){return `<section class="panel agenda-maintenance"><div class="section-title"><div><h2>Manutenção da Casa</h2><p class="subtle">Rotinas podem ser agrupadas em blocos de manutenção.</p></div><button class="secondary" data-agenda-action="add-maintenance">Adicionar rotina</button></div><div class="maintenance-list">${db.maintenanceRoutines.filter(item=>item.active).map(item=>`<label><input type="checkbox" data-maintenance-id="${item.id}" ${item.completedDates?.includes(localDate(new Date()))?"checked":""}><span>${esc(item.title)}</span><small>${item.frequency.count}× ${item.frequency.type==="daily"?"ao dia":item.frequency.type==="weekly"?"por semana":"por mês"} · ${item.estimatedMinutes} min</small></label>`).join("")}</div></section>`}
function renderAgendaPage(db){ensureAgendaData(db);visibleWeek=visibleWeek||monday(new Date());const start=monday(visibleWeek),end=addDays(start,6);return `<section class="page-head compact agenda-head"><div><p class="eyebrow">PLANEJAMENTO DE ATENÇÃO</p><h1>Semana</h1><p class="subtle">${new Intl.DateTimeFormat("pt-BR",{day:"numeric",month:"short"}).format(start)} a ${new Intl.DateTimeFormat("pt-BR",{day:"numeric",month:"short",year:"numeric"}).format(end)}</p></div><div class="header-actions"><button class="secondary" data-agenda-action="prev-week">←</button><button class="secondary" data-agenda-action="today-week">Hoje</button><button class="secondary" data-agenda-action="next-week">→</button><button class="secondary" data-agenda-action="plan-week">Planejar semana</button><button class="secondary" data-agenda-action="replan-day">Reorganizar hoje</button><button class="primary" data-agenda-action="new">Novo bloco</button></div></section>${balanceCards(db,start)}<section class="panel agenda-calendar"><div class="agenda-legend">${Object.entries(BLOCK_TYPES).map(([key,value])=>`<span class="type-${key}">${value}</span>`).join("")}</div>${weekGrid(db,start)}</section>${maintenancePanel(db)}`}

function agendaConflicts(db){const blocks=blocksForWeek(db,visibleWeek||new Date()).filter(block=>!["margin","reservable"].includes(block.blockType)),conflicts=[];for(let i=0;i<blocks.length;i++)for(let j=i+1;j<blocks.length;j++){const a=blocks[i],b=blocks[j];if(a.date===b.date&&minutes(a.startTime)<minutes(b.endTime)&&minutes(b.startTime)<minutes(a.endTime))conflicts.push([a,b])}return conflicts}
function mountAgendaPage(db){const main=document.querySelector(".main-content");if(!main)return;main.innerHTML=renderAgendaPage(db);const conflicts=agendaConflicts(db);if(conflicts.length){const notice=document.createElement("div");notice.className="agenda-conflict-note";notice.innerHTML=`<b>${conflicts.length} conflito(s) para revisar</b><span>Nenhum bloco foi removido ou movido automaticamente.</span>`;main.querySelector(".agenda-calendar")?.before(notice)}}
function augmentAgendaNavigation(page){document.querySelectorAll(".sidebar nav,.mobile-nav").forEach(nav=>{if(nav.querySelector('[data-page="semana"]'))return;const button=document.createElement("button");button.className=`nav-item ${page==="semana"?"active":""}`;button.dataset.action="navigate";button.dataset.page="semana";button.innerHTML="<span>▦</span>Semana";const config=nav.querySelector('[data-page="config"]');nav.insertBefore(button,config||null)})}
function augmentTodayWithAgenda(db){const main=document.querySelector(".main-content");if(!main||main.querySelector("#agenda-today-bridge"))return;const {current,next}=currentAgendaState(db),states=responsibilityStates(db);const section=document.createElement("section");section.id="agenda-today-bridge";section.className="agenda-today-bridge";section.innerHTML=`<div class="section-title"><h2>Agenda de hoje</h2><button class="text-button" data-action="navigate" data-page="semana">Ver semana</button></div><div class="agenda-now-grid"><article class="panel"><p class="eyebrow">AGORA</p>${current?`<h2>${esc(current.title)}</h2><p>${label(RESPONSIBILITY_AREAS,current.responsibilityArea)} · ${label(BLOCK_TYPES,current.blockType)} até ${current.endTime}</p>${["focus","maintenance"].includes(current.blockType)?`<button class="primary" data-agenda-action="next" data-id="${esc(current.id)}">Escolher próxima ação</button>`:"<p class=\"subtle\">Este período protege presença e atenção.</p>"}`:"<h2>Sem bloco neste momento</h2><p class=\"subtle\">A margem também faz parte do planejamento.</p>"}</article><article class="panel"><p class="eyebrow">PRÓXIMO MARCO</p>${next?`<h2>${esc(next.title)}</h2><p>${new Intl.DateTimeFormat("pt-BR",{weekday:"short",day:"numeric"}).format(new Date(`${next.date}T12:00:00`))} · ${next.startTime}</p>`:"<h2>Semana aberta</h2><p class=\"subtle\">Nenhum compromisso próximo.</p>"}</article></div><div class="today-responsibilities">${states.map(item=>`<span class="${item.kind}">${label(RESPONSIBILITY_AREAS,item.area)} <b>${item.status}</b></span>`).join("")}</div>`;main.prepend(section)}

function blockModal(block={}){const recurrence=block.recurrenceId?null:undefined,dayChecks=[1,2,3,4,5,6,0].map(day=>`<label class="check"><input type="checkbox" name="daysOfWeek" value="${day}">${["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"][day]}</label>`).join("");const el=document.createElement("div");el.className="modal-backdrop";el.innerHTML=`<form class="modal" id="agenda-block-form"><div class="modal-head"><h2>${block.id?"Editar bloco":"Novo bloco"}</h2><button type="button" class="text-button" data-agenda-close>Fechar</button></div><input type="hidden" name="id" value="${esc(block.id||"")}"><input type="hidden" name="recurrenceId" value="${esc(block.recurrenceId||"")}"><input type="hidden" name="originalOccurrenceDate" value="${esc(block._virtual?block.date:block.originalOccurrenceDate||"")}"><div class="form-grid"><label>Título<input name="title" value="${esc(block.title||"")}" placeholder="Ex.: Foco Geld"></label><label>Responsabilidade<select name="responsibilityArea">${Object.entries(RESPONSIBILITY_AREAS).map(([key,value])=>`<option value="${key}" ${block.responsibilityArea===key?"selected":""}>${value}</option>`).join("")}</select></label><label>Tipo<select name="blockType">${Object.entries(BLOCK_TYPES).map(([key,value])=>`<option value="${key}" ${block.blockType===key?"selected":""}>${value}</option>`).join("")}</select></label><label>Rigidez<select name="rigidity">${Object.entries(BLOCK_RIGIDITIES).map(([key,value])=>`<option value="${key}" ${block.rigidity===key?"selected":""}>${value}</option>`).join("")}</select></label><label>Data<input required type="date" name="date" value="${block.date||localDate(new Date())}"></label><label>Início<input required type="time" name="startTime" value="${block.startTime||"09:00"}"></label><label>Fim<input required type="time" name="endTime" value="${block.endTime||"10:00"}"></label><label class="wide">Observação<textarea name="notes">${esc(block.notes||"")}</textarea></label><fieldset class="context-field"><legend>Repetir semanalmente</legend><label class="check"><input type="checkbox" name="repeatWeekly"> Criar recorrência</label>${dayChecks}<label>Até<input type="date" name="endDate"></label></fieldset></div><p class="form-error"></p><div class="modal-actions"><button type="button" class="secondary" data-agenda-close>Cancelar</button><button class="primary">Salvar bloco</button></div></form>`;document.body.append(el);return el}
function findBlock(db,id){if(String(id).startsWith("rec:"))return blocksForWeek(db,visibleWeek||new Date()).find(block=>block.id===id);return db.scheduleBlocks.find(block=>block.id===id)}
function proposalModal(db){const states=responsibilityStates(db,visibleWeek||new Date()),start=monday(visibleWeek||new Date()),suggestions=[];const add=(day,startTime,endTime,area,type,title)=>suggestions.push({id:uid(),date:localDate(addDays(start,day)),startTime,endTime,responsibilityArea:area,blockType:type,rigidity:"flexible",title,status:"planned",allowNextAction:type==="focus",source:"suggestion"});if(!blocksForWeek(db,start).some(b=>b.responsibilityArea==="casa"))add(2,"13:00","13:40","casa","maintenance","Manutenção da Casa");const needy=states.filter(item=>["attention","low"].includes(item.kind)&&!["familia","casa"].includes(item.area)).slice(0,2);needy.forEach((item,index)=>add(3+index,"10:00","11:00",item.area,"focus",`Foco ${label(RESPONSIBILITY_AREAS,item.area)}`));add(3,"11:00","11:30","pessoal","margin","Margem preservada");const el=document.createElement("div");el.className="modal-backdrop";el.innerHTML=`<div class="modal"><div class="modal-head"><div><h2>Proposta para a semana</h2><p class="subtle">Revise antes de salvar. Nada foi confirmado ainda.</p></div><button class="text-button" data-agenda-close>Fechar</button></div><div class="proposal-list">${suggestions.map(item=>`<label><input type="checkbox" checked data-proposal-id="${item.id}"><span><b>${esc(item.title)}</b><small>${item.date} · ${item.startTime}–${item.endTime}</small></span></label>`).join("")||"<p class=\"empty-copy\">A semana já possui atenção distribuída.</p>"}</div><div class="modal-actions"><button class="secondary" data-agenda-close>Cancelar</button><button class="primary" data-accept-proposal>Aceitar selecionados</button></div></div>`;document.body.append(el);el.querySelector("[data-accept-proposal]")?.addEventListener("click",()=>{suggestions.filter(item=>el.querySelector(`[data-proposal-id="${item.id}"]`)?.checked).forEach(item=>saveAgendaBlock(db,item));el.remove();el.dispatchEvent(new CustomEvent("agenda-saved",{bubbles:true}))});return el}

function addAgendaConfig(db){
ensureAgendaData(db);
const grid=document.querySelector(".settings-grid");if(!grid||grid.querySelector("#agenda-settings-panel"))return;const panel=document.createElement("section");panel.className="panel";panel.id="agenda-settings-panel";panel.innerHTML=`<h2>Agenda</h2><p class="subtle">A agenda distribui atenção e preserva margem.</p><label>Ocupação máxima (%)<input name="agendaOccupancy" type="number" min="60" max="90" value="${Math.round(db.agendaSettings.maximumPlanningOccupancy*100)}"></label><label>Margem mínima (min)<input name="agendaMargin" type="number" min="15" value="${db.agendaSettings.minimumMarginMinutes}"></label><label>Foco mínimo (min)<input name="agendaFocus" type="number" min="30" value="${db.agendaSettings.minimumFocusMinutes}"></label><label>Penalidade de troca de contexto<input name="agendaSwitch" type="number" min="0" value="${db.agendaSettings.contextSwitchPenalty}"></label><div class="responsibility-settings">${Object.entries(RESPONSIBILITY_AREAS).map(([key,value])=>`<label class="check"><input type="checkbox" name="responsibility-${key}" ${db.agendaSettings.responsibilities[key]?.active!==false?"checked":""}>${value}</label>`).join("")}</div>`;grid.append(panel)}
function decorateTaskModal(db,modal){const form=modal?.querySelector("#task-form");if(!form||form.querySelector('[name="responsibilityArea"]'))return;const id=form.querySelector('[name="id"]')?.value,task=db.tasks.find(item=>item.id===id),labelEl=document.createElement("label");labelEl.innerHTML=`Área de responsabilidade<select name="responsibilityArea"><option value="">Não classificada</option>${Object.entries(RESPONSIBILITY_AREAS).map(([key,value])=>`<option value="${key}" ${task?.responsibilityArea===key?"selected":""}>${value}</option>`).join("")}</select>`;form.querySelector('[name="area"]')?.closest("label")?.before(labelEl);form.addEventListener("submit",()=>queueMicrotask(()=>{const saved=id?db.tasks.find(item=>item.id===id):[...db.tasks].reverse().find(item=>item.title===form.querySelector('[name="title"]')?.value.trim());if(saved){saved.responsibilityArea=form.querySelector('[name="responsibilityArea"]')?.value||null;saved.updatedAt=now();localStorage.setItem("proxima-acao-db",JSON.stringify({...db,version:2}))}}))}

function bindAgendaIntegration({db,persist,render,navigateToRecommendation,page}){document.querySelectorAll('[data-page="semana"]').forEach(button=>{if(button.dataset.agendaBound)return;button.dataset.agendaBound="1";button.addEventListener("click",()=>{})});document.querySelectorAll('[data-action="new-task"],[data-action="edit-task"]').forEach(button=>button.addEventListener("click",()=>queueMicrotask(()=>decorateTaskModal(db,document.querySelector(".modal-backdrop")))));document.querySelectorAll('[data-action="start-session"]').forEach(button=>button.addEventListener("click",()=>{if(db.currentSession&&activeAgendaContext){db.currentSession.scheduleBlockId=activeAgendaContext.scheduleBlockId;db.currentSession.responsibilityArea=activeAgendaContext.responsibilityArea;db.currentSession.recommendationSource="agenda";persist()}}));
const activeScheduleBlockId=db.currentSession?.scheduleBlockId;document.querySelectorAll('[data-action="finish-session"]').forEach(button=>button.addEventListener("click",()=>{if(!activeScheduleBlockId)return;const session=[...db.sessions].reverse().find(item=>item.scheduleBlockId===activeScheduleBlockId);if(!session)return;const block=db.scheduleBlocks.find(item=>item.id===activeScheduleBlockId);if(block){block.actualMinutes=executedForBlock(db,block.id);block.status=button.dataset.result==="concluida"?"partiallyCompleted":block.status;block.updatedAt=now();agendaHistory(db,"execution",block,{sessionId:session.id,minutes:session.executedMinutes});persist()}}));
document.querySelectorAll("[data-agenda-close]").forEach(button=>button.addEventListener("click",()=>button.closest(".modal-backdrop")?.remove()));document.querySelectorAll("[data-agenda-action]").forEach(button=>button.addEventListener("click",()=>{
const action=button.dataset.agendaAction,id=button.dataset.id;let block=findBlock(db,id);
if(action==="new"){const modal=blockModal();bindModal(modal)}else if(action==="edit"&&block){const modal=blockModal(block);bindModal(modal)}else if(action==="duplicate"&&block){saveAgendaBlock(db,{...block,id:null,recurrenceId:null,originalOccurrenceDate:null,title:`${block.title} (cópia)`});persist();render()}else if(action==="delete"&&block&&confirm(`Excluir "${block.title}"?`)){if(block._virtual)saveAgendaBlock(db,{...block,id:null,status:"cancelled",originalOccurrenceDate:block.date});else db.scheduleBlocks=db.scheduleBlocks.filter(item=>item.id!==block.id);agendaHistory(db,"cancelled",block);persist();render()}else if(action==="complete"&&block){if(block._virtual)block=saveAgendaBlock(db,{...block,id:null,originalOccurrenceDate:block.date});block.status="completed";block.updatedAt=now();agendaHistory(db,"completed",block);persist();render()}else if(action==="partial"&&block){if(block._virtual)block=saveAgendaBlock(db,{...block,id:null,originalOccurrenceDate:block.date});block.status="partiallyCompleted";block.updatedAt=now();agendaHistory(db,"partiallyCompleted",block);persist();render()}else if(action==="convert"&&block){if(block._virtual)block=saveAgendaBlock(db,{...block,id:null,originalOccurrenceDate:block.date});block.blockType="fixed";block.rigidity="rigid";block.confirmedExternalEvent=true;block.title=prompt("Título do compromisso",block.title)||block.title;block.updatedAt=now();agendaHistory(db,"converted",block);persist();render()}
else if(action==="next"&&block){if(block._virtual)block=saveAgendaBlock(db,{...block,id:null,originalOccurrenceDate:block.date});activeAgendaContext={scheduleBlockId:block.id,responsibilityArea:block.responsibilityArea,availableMinutes:Math.max(15,Math.min(60,duration(block)-executedForBlock(db,block.id)))};persist();navigateToRecommendation(activeAgendaContext)}
else if(action==="prev-week"){visibleWeek=addDays(visibleWeek||new Date(),-7);render()}else if(action==="next-week"){visibleWeek=addDays(visibleWeek||new Date(),7);render()}else if(action==="today-week"){visibleWeek=monday(new Date());render()}else if(action==="plan-week"){const modal=proposalModal(db);modal.addEventListener("agenda-saved",()=>{persist();render()});modal.querySelectorAll("[data-agenda-close]").forEach(x=>x.addEventListener("click",()=>modal.remove()))}else if(action==="replan-day"){const today=localDate(new Date()),movable=db.scheduleBlocks.filter(item=>item.date===today&&item.status==="planned"&&item.rigidity==="flexible");if(!movable.length){alert("Não há blocos flexíveis restantes para reorganizar hoje.");return}if(confirm(`Mover ${movable.length} bloco(s) flexível(is) para amanhã, preservando os rígidos?`)){movable.forEach(item=>{agendaHistory(db,"moved",item,{fromDate:item.date});item.date=localDate(addDays(new Date(`${item.date}T12:00:00`),1));item.status="moved";const copy=saveAgendaBlock(db,{...item,id:null,status:"planned",source:"replan"});copy.movedFromId=item.id});persist();render()}}else if(action==="add-maintenance"){const title=prompt("Nome da rotina de manutenção");if(title){db.maintenanceRoutines.push({id:uid(),title,responsibilityArea:"casa",frequency:{type:"weekly",count:1},estimatedMinutes:30,preferredDays:[],completedDates:[],lastCompletedAt:null,active:true,createdAt:now(),updatedAt:now()});persist();render()}}}));document.querySelectorAll("[data-maintenance-id]").forEach(input=>input.addEventListener("change",()=>{const routine=db.maintenanceRoutines.find(item=>item.id===input.dataset.maintenanceId),today=localDate(new Date());if(!routine)return;routine.completedDates=[...new Set((routine.completedDates||[]).filter(date=>date!==today).concat(input.checked?[today]:[]))];routine.lastCompletedAt=input.checked?now():routine.lastCompletedAt;persist();render()}));if(page==="config")addAgendaConfig(db);function bindModal(modal){modal.querySelectorAll("[data-agenda-close]").forEach(button=>button.addEventListener("click",()=>modal.remove()));modal.querySelector("form").addEventListener("submit",event=>{event.preventDefault();const data=new FormData(event.currentTarget),start=data.get("startTime"),end=data.get("endTime"),error=event.currentTarget.querySelector(".form-error");if(minutes(end)<=minutes(start)){error.textContent="O fim precisa ser posterior ao início.";return}const value=Object.fromEntries(data.entries());
if(data.get("repeatWeekly")==="on"){const days=data.getAll("daysOfWeek");if(!days.length)days.push(new Date(`${value.date}T12:00:00`).getDay());const recurrence=saveAgendaRecurrence(db,{...value,name:value.title,daysOfWeek:days,startDate:value.date});value.recurrenceId=recurrence.id;value.originalOccurrenceDate=value.date}
saveAgendaBlock(db,value);persist();modal.remove();render()})}}
function saveAgendaSettings(db,form){const data=new FormData(form);db.agendaSettings.maximumPlanningOccupancy=Math.max(.6,Math.min(.9,Number(data.get("agendaOccupancy")||75)/100));db.agendaSettings.minimumMarginMinutes=Number(data.get("agendaMargin")||30);db.agendaSettings.minimumFocusMinutes=Number(data.get("agendaFocus")||60);db.agendaSettings.contextSwitchPenalty=Number(data.get("agendaSwitch")||20);Object.keys(RESPONSIBILITY_AREAS).forEach(key=>db.agendaSettings.responsibilities[key].active=data.get(`responsibility-${key}`)==="on")}
function getAgendaContext(){return activeAgendaContext}
function clearAgendaContext(){activeAgendaContext=null}
function augmentAgendaRecommendation(render){if(!activeAgendaContext)return;const main=document.querySelector(".main-content");if(!main||main.querySelector("#agenda-recommendation-context"))return;const banner=document.createElement("section");banner.id="agenda-recommendation-context";banner.className="panel agenda-context-banner";banner.innerHTML=`<div><p class="eyebrow">CONTEXTO DA AGENDA</p><b>${label(RESPONSIBILITY_AREAS,activeAgendaContext.responsibilityArea)}</b><span>${activeAgendaContext.availableMinutes} min disponíveis no bloco</span></div><button class="secondary">Ver tarefas de outras áreas</button>`;banner.querySelector("button").addEventListener("click",()=>{activeAgendaContext=null;render()});main.prepend(banner)}

function runAgendaTests(){const db={tasks:[],sessions:[],settings:{},scheduleBlocks:[],scheduleRecurrences:[],maintenanceRoutines:[],agendaHistory:[],agendaSettings:null};ensureAgendaData(db);const week=blocksForWeek(db,new Date("2026-08-10T12:00:00"));const mondayBlocks=week.filter(block=>block.date==="2026-08-10");const physio=mondayBlocks.find(block=>block.title==="Fisioterapia");const family=mondayBlocks.find(block=>block.responsibilityArea==="familia");const states=responsibilityStates(db,new Date("2026-08-10T12:00:00"));return {passed:!!physio&&!!family&&states.length===5&&db.maintenanceRoutines.length>=10,weekBlocks:week.length,states:states.map(item=>item.status)}}







