let db = loadDatabase(), page = "hoje", recommendation = null;
window.runRecommendationTests = runRecommendationTests;
const persist = () => saveDatabase(db);
function render() { document.querySelector("#app").innerHTML = renderApp(db, page, recommendation); bind(); if (db.currentSession) tickTimer(); }
function inputForRecommendation() { return { duration: Number(db.preferences.duration), energy: Number(db.preferences.energy), contexts: db.preferences.contexts || [] }; }
function findRecommendation(area = null) { const source = area ? { ...db, tasks: db.tasks.filter(t => t.area === area) } : db; recommendation = recommend(source, inputForRecommendation()); page = "recomendar"; render(); }
function startSession(taskId) { const task = db.tasks.find(t => t.id === taskId); if (!task) return; const part = recommendation?.parts?.find(p=>p.task.id === taskId), next = recommendation?.parts?.find(p=>p.task.id !== taskId); const planned = part && recommendation.parts.length > 1 ? 30 : db.preferences.duration; db.currentSession = { ...createSession({ taskId: task.id, taskTitleSnapshot: task.title, area: task.area, subarea: task.subarea, plannedMinutes: planned, initialEnergy: db.preferences.energy, availableContexts: db.preferences.contexts, recommendationSource: "motor", rejectionCount: db.cycle.rejectionCount }), queuedTaskId: next?.task.id || null }; task.status = "em_andamento"; task.updatedAt = now(); persist(); render(); }
function finishSession(result) { const current = db.currentSession; if (!current) return; clearInterval(window.proximaTimer); const elapsed = Math.max(0, Math.min(current.plannedMinutes, Math.floor((Date.now() - new Date(current.startedAt)) / 60000))); const executed = result === "cancelada" ? elapsed : Math.max(1, elapsed); const session = { ...current, endedAt: now(), executedMinutes: executed, pauseMinutes: result === "concluida" ? Math.max(0, current.plannedMinutes - executed) : 0, result, interrupted: result === "interrompida" }; session.validFrequencySession = isValidFrequencySession(session, db.settings); db.sessions.push(session); const task = db.tasks.find(t=>t.id===current.taskId); if (task) { task.lastExecutedAt = now(); task.updatedAt = now(); if (result === "concluida" && isMonthlyRequired(task)) completeMonthlyCycle(task, new Date(current.startedAt)); else if (result === "concluida") task.status = "concluida"; else if (result === "interrompida" || result === "avancou") task.status = "em_andamento"; }
 const queued = current.queuedTaskId; db.currentSession = null; db.cycle = { rejectedTaskIds: [], rejectionCount: 0 }; persist(); recommendation = null; page = "hoje"; render(); toast(result === "concluida" && session.pauseMinutes ? `Sessão registrada. ${session.pauseMinutes} min restantes viraram pausa.` : "Sessão registrada com o tempo real."); if (queued && result !== "cancelada" && confirm("Primeira parte concluída. Quer iniciar a segunda parte agora?")) { recommendation = { parts: [], task: db.tasks.find(t=>t.id===queued) }; startSession(queued); } }
function showRejectModal() { const el=document.createElement("div"); el.className="modal-backdrop"; el.innerHTML=`<div class="modal small-modal"><div class="modal-head"><h2>Por que esta sugestão não funciona agora?</h2><button class="text-button" data-close-modal>Fechar</button></div><div class="reason-buttons">${[["energia","Não tenho energia"],["contexto","Não tenho o contexto necessário"],["tempo","O tempo é insuficiente"],["definicao","A tarefa está mal definida"],["agora","Não quero fazer agora"],["relevante","A tarefa não é mais relevante"]].map(([v,l])=>`<button class="secondary" data-action="rejection-reason" data-reason="${v}">${l}</button>`).join("")}</div></div>`; document.body.append(el); }
function reject(reason) { const task = recommendation?.task; if (reason === "definicao" && task) task.needsReview = true; if (reason === "agora" && task) task.temporaryPenaltyUntil = new Date(Date.now()+4*3600000).toISOString(); if (reason === "relevante" && task && confirm("Arquivar esta tarefa?")) task.status="arquivada"; if (reason === "energia") db.preferences.energy = Math.max(1, db.preferences.energy-1); if (reason === "tempo") db.preferences.duration = db.preferences.duration === 60 ? 30 : 15; if (task) db.cycle.rejectedTaskIds.push(task.id); db.cycle.rejectionCount=0; document.querySelector(".modal-backdrop")?.remove(); persist(); findRecommendation(); }
function saveTask(form) { const data = new FormData(form), title=data.get("title")?.trim(), url=data.get("evernoteUrl")?.trim(), area=data.get("area"), requestedSubarea=data.get("subarea"), subarea=SUBAREAS[area]?.includes(requestedSubarea) ? requestedSubarea : SUBAREAS[area]?.[0]; const error=form.querySelector(".form-error"); if (!title) { error.textContent="Informe o título da tarefa."; return; } let task=db.tasks.find(t=>t.id===data.get("id")); const values={ title, evernoteUrl:url, area, subarea, minimumBlockMinutes:Number(data.get("minimumBlockMinutes")), estimatedTotalMinutes:Number(data.get("estimatedTotalMinutes")), energyRequired:Number(data.get("energyRequired")), priority:data.get("priority"), deadline:data.get("deadline"), recurrence:data.get("monthlyRequired")==="on" ? { frequency:"monthly", required:true, dueDay:Math.max(1,Math.min(31,Number(data.get("monthlyDueDay")||1))), completedPeriods:task?.recurrence?.completedPeriods || [] } : null, initialAction:data.get("initialAction"), notes:data.get("notes"), contexts:data.getAll("contexts"), manuallyCritical:data.get("manuallyCritical")==="on", updatedAt:now() }; if (task) Object.assign(task,values); else { task=createTask(values); db.tasks.push(task); } persist(); document.querySelector(".modal-backdrop")?.remove(); render(); toast("Tarefa salva."); }
function completeRecurringTask(taskId) { const task = db.tasks.find(item => item.id === taskId); if (!task || !isMonthlyRequired(task)) return; if (!confirm(`Concluir o ciclo mensal de "${task.title}"?`)) return; completeMonthlyCycle(task); persist(); render(); toast("Ciclo mensal concluído. A tarefa volta no próximo mês."); }
function openTaskModal(task) { const modal = taskModal(task); modal.querySelectorAll("[data-close-modal]").forEach(button => button.addEventListener("click", () => modal.remove())); modal.querySelector("#task-form").addEventListener("submit", event => { event.preventDefault(); saveTask(event.currentTarget); }); }
function normalizeTag(value) { return String(value || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[\s-]+/g, "_"); }
function mapImportedNote(title, tags) { const normalized = tags.map(normalizeTag); const area = ["trabalho", "organizacao", "estudo", "leitura", "lazer"].find(value => normalized.includes(value)) || "trabalho"; const aliases = { administracao: "administracao", operacional: "operacional", marketing: "marketing", desenvolvimento_da_empresa: "desenvolvimento_empresa", organizacao_de_trabalho: "organizacao_trabalho", linguas: "linguas", idiomas: "linguas", piano: "piano", livro_tecnico: "livro_tecnico", concurso: "concurso", filmes_e_series: "filmes_series", jogos: "jogos", outro: "outro" }; const subarea = normalized.map(tag => aliases[tag]).find(value => value && SUBAREAS[area].includes(value)) || SUBAREAS[area][0]; return { title, area, subarea, evernoteUrl: "", contexts: [] }; }
function showImportedNotes(notes) { const escapeText = value => String(value).replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char])); const modal = document.createElement("div"); modal.className = "modal-backdrop"; modal.innerHTML = `<div class="modal import-modal"><div class="modal-head"><div><h2>Notas encontradas</h2><p class="subtle">Escolha uma nota para preencher o cadastro. O link do Evernote ficará opcional.</p></div><button class="text-button" data-close-modal>Fechar</button></div><div class="import-list">${notes.map((note,index) => `<article><div><strong>${escapeText(note.title)}</strong><p>${escapeText(note.tags.join(" · ") || "Sem etiquetas")} → ${escapeText(note.area)} / ${escapeText(note.subarea)}</p></div><button class="secondary" data-import-note="${index}">Usar esta nota</button></article>`).join("")}</div></div>`; document.body.append(modal); modal.querySelector("[data-close-modal]").addEventListener("click", () => modal.remove()); modal.querySelectorAll("[data-import-note]").forEach(button => button.addEventListener("click", () => { const note = notes[Number(button.dataset.importNote)]; modal.remove(); openTaskModal(note); })); }
function importEvernote() { const input = document.createElement("input"); input.type = "file"; input.accept = ".enex,application/xml,text/xml"; input.addEventListener("change", async () => { const file = input.files?.[0]; if (!file) return; try { const xml = new DOMParser().parseFromString(await file.text(), "application/xml"); if (xml.querySelector("parsererror")) throw new Error("Não consegui ler este arquivo ENEX."); const notes = [...xml.querySelectorAll("note")].map(note => { const title = note.querySelector("title")?.textContent?.trim(); const tags = [...note.querySelectorAll(":scope > tag")].map(tag => tag.textContent.trim()); return title ? { ...mapImportedNote(title, tags), tags } : null; }).filter(Boolean); if (!notes.length) throw new Error("Nenhuma nota com título foi encontrada."); showImportedNotes(notes); } catch (error) { toast(error.message || "Não foi possível importar este arquivo."); } }); input.click(); }
function updateSettings(form) { const f=new FormData(form); for (const area of ["trabalho","organizacao","estudo","leitura"]) { db.settings.goals[area].minimumMinutes=Number(f.get(`${area}-minimum`)); db.settings.goals[area].targetMinutes=Number(f.get(`${area}-target`)); } persist(); toast("Metas salvas."); }
function updateTaskList() { filterTasks(); }
function bind() { document.querySelectorAll("[data-action]").forEach(el=>el.addEventListener("click",event=>{ const action=el.dataset.action, id=el.dataset.taskId; if (action === "import-evernote") { importEvernote(); return; } if (action === "export-mobile") { downloadJson(exportMobilePackage(db), `proxima-acao-mobile-package-${new Date().toISOString().slice(0,10)}.json`); toast("Pacote para celular exportado."); return; } if (action === "complete-recurring-task") { completeRecurringTask(id); return; } if (action === "navigate") { page=el.dataset.page; recommendation=null; render(); } else if (action === "clear-recommendation") { recommendation=null; render(); } else if (action === "toggle-details") { const details = document.querySelector("#decision-details"); if (details) details.open = !details.open; } else if (action === "start-session") startSession(id); else if (action === "switch-recommendation") { if (recommendation?.task) { db.cycle.rejectionCount++; db.cycle.rejectedTaskIds.push(recommendation.task.id); persist(); if (db.cycle.rejectionCount>=2) showRejectModal(); else findRecommendation(); } } else if (action === "rejection-reason") reject(el.dataset.reason); else if (action === "manual-area") manualAreaModal(); else if (action === "new-task") openTaskModal(); else if (action === "edit-task") openTaskModal(db.tasks.find(t=>t.id===id)); else if (action === "complete-task" || action === "archive-task") { const t=db.tasks.find(t=>t.id===id); if (t && (action === "complete-task" || confirm("Arquivar esta tarefa?"))) { t.status=action === "complete-task" ? "concluida":"arquivada"; t.updatedAt=now(); persist(); render(); toast("Tarefa atualizada."); } } else if (action === "load-demo") { if (!db.tasks.length || confirm("Adicionar dados de demonstração às tarefas atuais?")) { db.tasks.push(...seedTasks()); persist(); render(); toast("Dados de demonstração carregados."); } } else if (action === "export-data") downloadJson(exportData(db),`proxima-acao-backup-${new Date().toISOString().slice(0,10)}.json`); else if (action === "clear-data") { const typed=prompt("Digite APAGAR para remover todos os dados deste navegador."); if (typed === "APAGAR") { db=clearData(); recommendation=null; page="hoje"; render(); toast("Dados removidos."); } } else if (action === "delete-session") { if (confirm("Excluir este registro?")) { db.sessions=db.sessions.filter(s=>s.id!==el.dataset.sessionId); persist(); render(); } } else if (action === "finish-session") finishSession(el.dataset.result); }));
 document.querySelectorAll("[data-choice]").forEach(el=>el.addEventListener("click",()=>{ db.preferences[el.dataset.choice]=Number(el.dataset.value); document.querySelectorAll(`[data-choice="${el.dataset.choice}"]`).forEach(x=>x.classList.toggle("selected",x===el)); })); document.querySelectorAll("[data-context]").forEach(el=>el.addEventListener("click",()=>{ const c=el.dataset.context, set=new Set(db.preferences.contexts); set.has(c)?set.delete(c):set.add(c); db.preferences.contexts=[...set]; el.classList.toggle("selected",set.has(c)); }));
 document.querySelector("#recommend-form")?.addEventListener("submit",e=>{ e.preventDefault(); persist(); findRecommendation(); }); document.querySelectorAll("#task-search,#task-area-filter,#task-status-filter").forEach(el=>el.addEventListener("input",updateTaskList)); document.querySelector("#task-form")?.addEventListener("submit",e=>{ e.preventDefault(); saveTask(e.currentTarget); }); document.querySelectorAll("[data-close-modal]").forEach(el=>el.addEventListener("click",()=>el.closest(".modal-backdrop").remove())); document.querySelector("#settings-form")?.addEventListener("submit",e=>{ e.preventDefault(); updateSettings(e.currentTarget); }); document.querySelector("#mobile-update-file")?.addEventListener("change",async e=>{ const file=e.target.files[0]; if (!file) return; try { mergeMobileUpdate(db, JSON.parse(await file.text())); render(); toast("Atualização do celular incorporada."); } catch(err) { toast(err.message || "Não foi possível importar a atualização."); } finally { e.target.value=""; } }); document.querySelector("#import-file")?.addEventListener("change",async e=>{ const file=e.target.files[0]; if (!file) return; try { const incoming=JSON.parse(await file.text()); if (!confirm(`Importar ${incoming.tasks?.length||0} tarefas e ${incoming.sessions?.length||0} sessões? Um backup automático será criado.`)) return; db=importData(incoming); recommendation=null; render(); toast("Dados importados."); } catch(err) { toast(err.message || "Não foi possível importar este arquivo."); } finally { e.target.value=""; } }); }
function manualAreaModal() { const el=document.createElement("div"); el.className="modal-backdrop"; el.innerHTML=`<div class="modal small-modal"><div class="modal-head"><h2>Escolha uma área</h2><button class="text-button" data-close-modal>Fechar</button></div><div class="reason-buttons">${Object.entries({trabalho:"Trabalho",organizacao:"Organização",estudo:"Estudo",leitura:"Leitura",lazer:"Lazer"}).map(([v,l])=>`<button class="secondary" data-manual-area="${v}">${l}</button>`).join("")}</div></div>`; document.body.append(el); el.querySelectorAll("[data-manual-area]").forEach(b=>b.addEventListener("click",()=>{el.remove(); findRecommendation(b.dataset.manualArea);})); el.querySelector("[data-close-modal]").addEventListener("click",()=>el.remove()); }
function tickTimer() { const el=document.querySelector("#timer-display"); if (!el || !db.currentSession) return; const update=()=>{ if (!db.currentSession) { clearInterval(window.proximaTimer); return; } const remaining=Math.max(0,db.currentSession.plannedMinutes-Math.floor((Date.now()-new Date(db.currentSession.startedAt))/60000)); el.textContent=`${String(Math.floor(remaining/60)).padStart(2,"0")}:${String(remaining%60).padStart(2,"0")}`; if (remaining <= 0) toast("Seu bloco chegou ao fim. Registre como foi."); }; update(); clearInterval(window.proximaTimer); window.proximaTimer=setInterval(update,1000); }
render();







