const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const now = () => new Date().toISOString();
function createTask(data = {}) { return { id: uid(), title: "", evernoteUrl: "", area: "trabalho", subarea: "operacional", language: "", minimumBlockMinutes: 30, estimatedTotalMinutes: 60, contexts: [], energyRequired: 2, priority: "normal", deadline: "", recurrence: null, manuallyCritical: false, initialAction: "", notes: "", status: "ativa", needsReview: false, temporaryPenaltyUntil: null, createdAt: now(), updatedAt: now(), lastExecutedAt: null, ...data }; }
const monthKey = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
const isMonthlyRequired = task => task.recurrence?.frequency === "monthly" && task.recurrence?.required === true;
const isMonthlyCompleted = (task, date = new Date()) => isMonthlyRequired(task) && (task.recurrence.completedPeriods || []).includes(monthKey(date));
function monthlyDueDate(task, date = new Date()) { const dueDay = Math.max(1, Math.min(31, Number(task.recurrence?.dueDay || 1))); const lastDay = new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate(); return new Date(date.getFullYear(), date.getMonth(), Math.min(dueDay, lastDay), 23, 59, 59); }
function completeMonthlyCycle(task, date = new Date()) { if (!isMonthlyRequired(task)) return; const completedPeriods = [...new Set([...(task.recurrence.completedPeriods || []), monthKey(date)])]; task.recurrence = { ...task.recurrence, completedPeriods }; task.status = "ativa"; task.updatedAt = now(); }
function createSession(data = {}) { return { id: uid(), taskId: null, taskTitleSnapshot: "", area: "", subarea: "", startedAt: now(), endedAt: now(), plannedMinutes: 30, executedMinutes: 0, pauseMinutes: 0, result: "concluida", initialEnergy: 2, availableContexts: [], recommendationSource: "motor", recommendationAccepted: true, rejectionCount: 0, rejectionReason: null, interrupted: false, validFrequencySession: false, notes: "", ...data }; }
function createDatabase() { return { version: 1, settings: structuredClone(DEFAULT_SETTINGS), tasks: [], sessions: [], currentSession: null, cycle: { rejectedTaskIds: [], rejectionCount: 0 }, preferences: { contexts: ["computador", "internet"], energy: 2, duration: 30 }, createdAt: now() }; }

