const priority = { normal: 10, alta: 30, critica: 70 };
function urgency(task, date = new Date()) { if (!task.deadline) return { score: 0, label: "Sem prazo" }; const days = Math.ceil((new Date(`${task.deadline}T23:59:59`) - new Date(date)) / 86400000); if (days < 0) return { score: 60, label: "Vencida" }; if (days === 0) return { score: 50, label: "Vence hoje" }; if (days <= 2) return { score: 35, label: "Vence em até 2 dias" }; if (days <= 7) return { score: 20, label: "Vence em até 7 dias" }; return { score: 5, label: "Prazo distante" }; }
function hasCritical(tasks) { return tasks.some(t => t.manuallyCritical || t.priority === "critica" || urgency(t).score >= 50); }
function evaluateLeisureAvailability(db, input, date = new Date()) { const sessions = weekSessions(db, date), work = getAreaState(db, "trabalho", date), today = sessions.filter(s => sameDay(s.startedAt, date)), workToday = minutesFor(today, "trabalho"), productiveAfterLeisure = (() => { const last = [...db.sessions].filter(s => s.area === "lazer").sort((a,b) => new Date(b.startedAt)-new Date(a.startedAt))[0]; return today.some(s => s.area !== "lazer" && (!last || new Date(s.startedAt) > new Date(last.startedAt))); })(); const compatibleCritical = db.tasks.filter(t => t.status === "ativa" || t.status === "em_andamento").filter(t => t.minimumBlockMinutes <= input.duration && t.contexts.every(c => input.contexts.includes(c))).filter(t => t.manuallyCritical || t.priority === "critica" || urgency(t, date).score >= 50); if (["Criticamente atrasada", "Atrasada"].includes(work.state)) return { status: "blocked", reasons: ["Trabalho está atrasado; lazer só pode ser registrado como recuperação excepcional."] }; const threshold = work.state === "Adiantada" || work.state === "Meta atingida" ? 120 : 180; if (workToday < threshold) return { status: "blocked", reasons: [`Complete ${threshold} minutos de trabalho hoje para liberar lazer.`] }; if (compatibleCritical.length) return { status: "blocked", reasons: ["Há uma tarefa crítica executável agora."] }; if (!productiveAfterLeisure) return { status: "blocked", reasons: ["Faça uma atividade produtiva desde o último lazer."] }; const otherCritical = ["trabalho", "organizacao", "estudo", "leitura"].some(a => getAreaState(db, a, date).state === "Criticamente atrasada"); return { status: input.energy === 1 && !otherCritical ? "recommended" : "allowed", reasons: [input.energy === 1 ? "Sua energia está baixa e as áreas prioritárias estão atendidas." : "Lazer está liberado como alternativa consciente."] }; }
function eligibleTasks(db, input, date) { const leisure = evaluateLeisureAvailability(db, input, date); return db.tasks.filter(t => ["ativa", "em_andamento"].includes(t.status) && !isMonthlyCompleted(t, date) && t.minimumBlockMinutes <= input.duration && t.contexts.every(c => input.contexts.includes(c)) && !db.cycle.rejectedTaskIds.includes(t.id)).filter(t => t.area !== "lazer" || leisure.status !== "blocked").filter(t => t.energyRequired <= input.energy || t.manuallyCritical || t.priority === "critica"); }
function areaScore(db, area, tasks, input, date) { const state = getAreaState(db, area, date), s = db.settings.scoring, sessions = weekSessions(db, date); let score = db.settings.areaWeights[area] || 0, reasons = []; if (area !== "lazer") { if (state.done < state.minimum) { score += s.belowMinimumBonus; reasons.push(`${AREA_LABELS[area]} ainda não atingiu o mínimo semanal`); } if (state.done < state.target) score += s.belowTargetBonus; if (state.state === "Criticamente atrasada") { score += s.rhythmCriticalBonus; reasons.push(`${AREA_LABELS[area]} está criticamente atrasada`); } else if (state.state === "Atrasada") { score += s.rhythmBehindBonus; reasons.push(`${AREA_LABELS[area]} está abaixo do ritmo semanal`); } if (state.state === "Meta atingida") score -= s.targetReachedPenalty; }
 if (area === "trabalho") { const today = minutesFor(sessions.filter(x => sameDay(x.startedAt, date)), "trabalho"); if (today >= db.settings.goals.trabalho.dailyMaximumMinutes && !hasCritical(tasks)) return { score: -9999, reasons: ["Limite diário de trabalho atingido"] }; if (today >= db.settings.goals.trabalho.dailySecondThresholdMinutes) score -= s.workAfterFourHoursPenalty; else if (today >= db.settings.goals.trabalho.dailySoftMinimumMinutes) score -= s.workAfterThreeHoursPenalty; if (tasks.some(t => t.manuallyCritical || t.priority === "critica")) score += s.criticalTaskBonus; }
 if (area === "organizacao" && validSessionsFor(sessions, "organizacao") < db.settings.goals.organizacao.minimumSessions) { score += s.frequencyPendingBonus; reasons.push("Organização precisa de sessões válidas"); }
 if (area === "estudo" && studyRows(db, date).some(r => r.sessions < r.goal)) { score += s.frequencyPendingBonus; reasons.push("Há frequência de estudo pendente"); }
 if (area === "lazer") { const leisure = evaluateLeisureAvailability(db, input, date); score += leisure.status === "recommended" ? 40 : 0; reasons.push(...leisure.reasons); }
 return { score, reasons, state }; }
function taskScore(db, task, input, area, date) { const s = db.settings.scoring, sessions = weekSessions(db, date), u = urgency(task, date); let score = priority[task.priority] + u.score, reasons = []; if (isMonthlyRequired(task)) { const daysToDue = Math.ceil((monthlyDueDate(task, date) - date) / 86400000); score += 45; reasons.push("Tarefa obrigatória mensal pendente"); if (daysToDue < 0) { score += 60; reasons.push("O vencimento mensal passou"); } else if (daysToDue <= 2) { score += 35; reasons.push("O vencimento mensal está próximo"); } else if (daysToDue <= 7) score += 15; } if (task.manuallyCritical) { score += 30; reasons.push("A tarefa foi marcada como crítica"); } if (u.score >= 20) reasons.push(u.label); if (task.minimumBlockMinutes === input.duration) { score += 18; reasons.push(`Cabe exatamente em ${input.duration} minutos`); } else score += 8; if (task.energyRequired <= input.energy) reasons.push("Sua energia atual é compatível"); else { score -= s.energyPenalty; reasons.push("É crítica, mas exige mais energia do que você informou"); }
 if (task.area === "estudo") { const f = db.settings.studyFrequency[task.subarea], done = validSessionsFor(sessions, "estudo", task.subarea); if (f && done < f.sessions) { score += 25 + (done === 0 ? 15 : 0); reasons.push(`${SUBAREA_LABELS[task.subarea]} ainda não atingiu a frequência semanal`); } }
 if (task.area === "trabalho" && db.settings.strategicWork[task.subarea] && validSessionsFor(sessions, "trabalho", task.subarea) < 1) { const last = sessions.filter(x => x.subarea === task.subarea).sort((a,b)=>new Date(b.startedAt)-new Date(a.startedAt))[0]; score += db.settings.strategicBonus.noSessionThisWeek; if (!last || (date - new Date(last.startedAt)) > 3*86400000) score += db.settings.strategicBonus.threeDaysWithoutActivity; if (!last || (date - new Date(last.startedAt)) > 5*86400000) score += db.settings.strategicBonus.fiveDaysWithoutActivity; if (date.getDay() === 0) score += db.settings.strategicBonus.sundayWithoutSession; reasons.push(`${SUBAREA_LABELS[task.subarea]} ainda não teve sessão estratégica nesta semana`); }
 if (task.lastExecutedAt) { const diff = Math.floor((new Date(date).setHours(0,0,0,0) - new Date(task.lastExecutedAt).setHours(0,0,0,0)) / 86400000); if (diff === 0 && task.status === "em_andamento") { score += s.continuitySameDay; reasons.push("Você começou esta tarefa hoje; aproveite a continuidade"); } else if (diff === 1) score += s.continuityPreviousDay; }
 if (task.needsReview) score -= s.refusalPenalty; if (task.temporaryPenaltyUntil && new Date(task.temporaryPenaltyUntil) > date) score -= s.refusalPenalty; return { task, score, reasons, urgency: u.label }; }
function recommend(db, input, date = new Date()) { const eligible = eligibleTasks(db, input, date); if (!eligible.length) return { empty: true, message: "Nenhuma tarefa corresponde ao seu tempo, energia e contextos atuais." }; const grouped = Object.groupBy ? Object.groupBy(eligible, t => t.area) : eligible.reduce((a,t) => ((a[t.area] ||= []).push(t),a),{}); const areas = Object.entries(grouped).map(([area, tasks]) => ({ area, tasks, ...areaScore(db, area, tasks, input, date) })).sort((a,b)=>b.score-a.score); const bestArea = areas[0], ranked = bestArea.tasks.map(t => taskScore(db, t, input, bestArea, date)).sort((a,b)=>b.score-a.score); let parts = [ranked[0]]; if (input.duration === 60) { const candidates = eligible.filter(t => t.minimumBlockMinutes <= 30).map(t => taskScore(db,t,{...input,duration:30},null,date)).sort((a,b)=>b.score-a.score); const pair = candidates.find(x => x.task.id !== ranked[0].task.id && (x.task.area !== ranked[0].task.area || x.task.subarea !== ranked[0].task.subarea)); if (pair && ranked[0].task.minimumBlockMinutes < 60 && ranked[0].score < (candidates[0]?.score + pair.score) * 1.25) parts = [candidates[0], pair]; }
 return { input, area: bestArea.area, areaScore: bestArea.score, task: parts[0].task, score: parts[0].score, reasons: [...bestArea.reasons, ...parts[0].reasons].slice(0,4), urgency: parts[0].urgency, alternatives: ranked.slice(1,3), parts, details: { areas: areas.map(x=>({area:x.area,score:x.score})), taskScore: parts[0].score } }; }
function runRecommendationTests() { console.group("Próxima Ação — testes manuais"); console.info("Use dados de demonstração e confira cenários no README."); console.groupEnd(); return true; }


