function loadDatabase() { try { const raw = localStorage.getItem(STORAGE_KEY); return raw ? migrate(JSON.parse(raw)) : createDatabase(); } catch { return createDatabase(); } }
function saveDatabase(db) { localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...db, version: DB_VERSION })); }
function migrate(db) { const base = createDatabase(); return { ...base, ...db, version: DB_VERSION, settings: { ...base.settings, ...(db.settings || {}) }, tasks: Array.isArray(db.tasks) ? db.tasks : [], sessions: Array.isArray(db.sessions) ? db.sessions : [], mobileActionReviews: Array.isArray(db.mobileActionReviews) ? db.mobileActionReviews : [] }; }
function exportData(db) { return { metadata: { appName: "Próxima Ação", databaseVersion: DB_VERSION, exportedAt: new Date().toISOString() }, settings: db.settings, tasks: db.tasks, sessions: db.sessions, currentSession: db.currentSession, preferences: db.preferences }; }
function validateImport(value) { return !!value && typeof value === "object" && Array.isArray(value.tasks) && Array.isArray(value.sessions) && value.settings; }
function importData(value) { if (!validateImport(value)) throw new Error("Arquivo incompatível."); localStorage.setItem(BACKUP_KEY, JSON.stringify({ backedUpAt: new Date().toISOString(), data: loadDatabase() })); const db = migrate(value); saveDatabase(db); return db; }
function clearData() { localStorage.removeItem(STORAGE_KEY); return createDatabase(); }
function downloadJson(value, name) { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }
function exportMobilePackage(db) { const start = new Date(); start.setDate(start.getDate() - ((start.getDay() + 6) % 7)); start.setHours(0, 0, 0, 0); return { metadata: { appName: "Próxima Ação", kind: "mobile-package", exportedAt: new Date().toISOString() }, settings: db.settings, tasks: db.tasks.filter(task => ["ativa", "em_andamento"].includes(task.status) || task.recurrence?.frequency === "monthly"), sessions: db.sessions.filter(session => new Date(session.startedAt) >= start), currentSession: null }; }
function mergeMobileUpdate(db, update) { if (update?.metadata?.kind !== "mobile-update" || !Array.isArray(update.sessions) || !Array.isArray(update.taskUpdates)) throw new Error("Arquivo de atualização mobile inválido."); const sessionIds = new Set(db.sessions.map(session => session.id)); const pendingMobileActions = []; db.mobileActionReviews ||= []; update.sessions.forEach(session => { if (sessionIds.has(session.id)) return; db.sessions.push(session); if (!session.taskId && session.manualActionId && !db.mobileActionReviews.some(review => review.manualActionId === session.manualActionId)) pendingMobileActions.push(session); }); update.taskUpdates.forEach(change => { const task = db.tasks.find(item => item.id === change.id); if (!task) return; if (change.recurrence?.completedPeriods) task.recurrence = { ...task.recurrence, ...change.recurrence, completedPeriods: [...new Set([...(task.recurrence?.completedPeriods || []), ...change.recurrence.completedPeriods])] }; if (!task.updatedAt || new Date(change.updatedAt || 0) >= new Date(task.updatedAt)) Object.assign(task, { status: change.status || task.status, lastExecutedAt: change.lastExecutedAt || task.lastExecutedAt, updatedAt: change.updatedAt || task.updatedAt }); }); saveDatabase(db); return { database: db, pendingMobileActions }; }

